-- =============================================================
-- VISTAS (VIEWS) - Muebleria Oracle 21c
-- Todas las consultas SELECT del sistema se ejecutan a través
-- de estas vistas. El backend nunca consulta tablas directamente.
-- Ejecutar como usuario: Muebleria
-- =============================================================

-- ─────────────────────────────────────────────────────────────
-- AUTENTICACIÓN / SEGURIDAD
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_LOGIN_USUARIO AS
SELECT U.ID_USUARIO,
       U.USERNAME_USUARIO,
       U.PASSWORD_USUARIO,
       U.EMAIL_USUARIO,
       U.ESTADO_USUARIO,
       U.ID_SUCURSAL,
       R.NOMBRE_ROL,
       C.ID_CLIENTE
FROM   USUARIOS U
JOIN   ROLES R    ON R.ID_ROL = U.ID_ROL
LEFT JOIN CLIENTE C ON LOWER(C.EMAIL_CLIENTE) = LOWER(U.EMAIL_USUARIO);
/

CREATE OR REPLACE VIEW VW_PERFIL_USUARIO AS
SELECT U.ID_USUARIO,
       U.USERNAME_USUARIO,
       U.EMAIL_USUARIO,
       U.ULTIMO_ACCESO_USUARIO,
       R.NOMBRE_ROL,
       S.NOMBRE_SUCURSAL
FROM   USUARIOS U
JOIN   ROLES      R ON R.ID_ROL      = U.ID_ROL
JOIN   SUCURSALES S ON S.ID_SUCURSAL = U.ID_SUCURSAL;
/

CREATE OR REPLACE VIEW VW_PERMISOS_USUARIO AS
SELECT DISTINCT U.ID_USUARIO,
                P.MODULO_PERMISO
FROM   PERMISOS P
JOIN   USUARIOS U ON U.ID_ROL = P.ID_ROL
WHERE  P.MODULO_PERMISO IS NOT NULL;
/

-- ─────────────────────────────────────────────────────────────
-- CONFIGURACIÓN GENERAL
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_EMPRESAS AS
SELECT ID_EMPRESA,
       NOMBRE_EMPRESA,
       NIT_EMPRESA,
       RAZON_SOCIAL_EMPRESA,
       DIRECCION_EMPRESA,
       LOGO_EMPRESA,
       ESTADO_EMPRESA
FROM   EMPRESAS;
/

CREATE OR REPLACE VIEW VW_SUCURSALES AS
SELECT S.ID_SUCURSAL,
       S.CODIGO_SUCURSAL,
       S.NOMBRE_SUCURSAL,
       S.DIRECCION_SUCURSAL,
       S.EMAIL_SUCURSAL,
       S.ESTADO_SUCURSAL,
       S.ID_EMPRESA,
       S.ID_MUNICIPIO,
       E.NOMBRE_EMPRESA
FROM   SUCURSALES S
JOIN   EMPRESAS   E ON E.ID_EMPRESA = S.ID_EMPRESA;
/

CREATE OR REPLACE VIEW VW_ROLES AS
SELECT ID_ROL,
       NOMBRE_ROL,
       DESCRIPCION_ROL,
       RANGO_ROL
FROM   ROLES;
/

CREATE OR REPLACE VIEW VW_USUARIOS AS
SELECT U.ID_USUARIO,
       U.USERNAME_USUARIO,
       U.EMAIL_USUARIO,
       U.ESTADO_USUARIO,
       U.ULTIMO_ACCESO_USUARIO,
       U.ID_ROL,
       U.ID_SUCURSAL,
       R.NOMBRE_ROL,
       S.NOMBRE_SUCURSAL
FROM   USUARIOS   U
JOIN   ROLES      R ON R.ID_ROL      = U.ID_ROL
JOIN   SUCURSALES S ON S.ID_SUCURSAL = U.ID_SUCURSAL;
/

CREATE OR REPLACE VIEW VW_PERMISOS AS
SELECT P.ID_PERMISO,
       P.NOMBRE_PERMISO,
       P.DESCRIPCION_PERMISO,
       P.MODULO_PERMISO,
       P.ESTADO,
       P.ID_ROL,
       R.NOMBRE_ROL
FROM   PERMISOS P
JOIN   ROLES    R ON R.ID_ROL = P.ID_ROL;
/

CREATE OR REPLACE VIEW VW_PERMISOS_MATRIZ AS
SELECT R.ID_ROL,
       R.NOMBRE_ROL,
       R.RANGO_ROL,
       P.ID_PERMISO,
       P.MODULO_PERMISO
FROM   ROLES R
LEFT JOIN PERMISOS P ON P.ID_ROL = R.ID_ROL
WHERE  LOWER(R.NOMBRE_ROL) NOT IN ('admin', 'cliente');
/

CREATE OR REPLACE VIEW VW_MONEDAS AS
SELECT ID_MONEDA,
       CODIGO_MONEDA,
       NOMBRE_MONEDA,
       SIMBOLO_MONEDA,
       DECIMALES_MONEDA
FROM   MONEDAS;
/

CREATE OR REPLACE VIEW VW_DEPARTAMENTOS AS
SELECT ID_DEPARTAMENTO,
       NOMBRE_DEPARTAMENTO,
       FRECUENCIA_DEPARTAMENTO,
       ZONA_TERRITORIAL_DEPARTAMENTO
FROM   DEPARTAMENTO;
/

CREATE OR REPLACE VIEW VW_MUNICIPIOS AS
SELECT M.ID_MUNICIPIO,
       M.NOMBRE_MUNICIPIO,
       M.CODIGO_POSTAL_MUNICIPIO,
       M.ID_DEPARTAMENTO,
       D.NOMBRE_DEPARTAMENTO
FROM   MUNICIPIOS  M
JOIN   DEPARTAMENTO D ON D.ID_DEPARTAMENTO = M.ID_DEPARTAMENTO;
/

-- ─────────────────────────────────────────────────────────────
-- RRHH
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_DEPARTAMENTOS_RRHH AS
SELECT D.ID_DEPARTAMENTO_RRHH,
       D.NOMBRE_DEPARTAMENTO_RRHH,
       D.CODIGO_DEPARTAMENTO_RRHH,
       D.ID_SUCURSAL,
       D.ID_DEPARTAMENTO_RRHH_PADRE,
       S.NOMBRE_SUCURSAL
FROM   DEPARTAMENTO_RRHH D
JOIN   SUCURSALES         S ON S.ID_SUCURSAL = D.ID_SUCURSAL;
/

CREATE OR REPLACE VIEW VW_CARGOS_RRHH AS
SELECT C.ID_CARGO_RRHH,
       C.NOMBRE_CARGO_RRHH,
       C.NIVEL_CARGO_RRHH,
       C.SALARIO_MIN_CARGO_RRHH,
       C.SALARIO_MAX_CARGO_RRHH,
       C.ID_DEPARTAMENTO_RRHH,
       D.NOMBRE_DEPARTAMENTO_RRHH
FROM   CARGO_RRHH        C
JOIN   DEPARTAMENTO_RRHH D ON D.ID_DEPARTAMENTO_RRHH = C.ID_DEPARTAMENTO_RRHH;
/

CREATE OR REPLACE VIEW VW_EMPLEADOS AS
SELECT E.ID_EMPLEADO,
       E.NUMERO_EMPLEADO,
       E.DPI_EMPLEADO,
       E.NOMBRES_EMPLEADO,
       E.APELLIDOS_EMPLEADO,
       E.FECHA_NACIMIENTO_EMPLEADO,
       E.GENERO_EMPLEADO,
       E.EMAIL_COORPORARIVO_EMPLEADO,
       E.FECHA_INGRESO_EMPLEADO,
       E.ESTADO_EMPLEADO,
       E.ID_CARGO,
       C.NOMBRE_CARGO_RRHH,
       D.NOMBRE_DEPARTAMENTO_RRHH
FROM   EMPLEADOS         E
LEFT JOIN CARGO_RRHH     C ON C.ID_CARGO_RRHH        = E.ID_CARGO
LEFT JOIN DEPARTAMENTO_RRHH D ON D.ID_DEPARTAMENTO_RRHH = C.ID_DEPARTAMENTO_RRHH;
/

CREATE OR REPLACE VIEW VW_JORNADAS AS
SELECT ID_JORNADA,
       NOMBRE_JORNADA,
       CODIGO_JORNADA,
       HORA_IN_JORNADA,
       JORA_FIN_JORNADA,
       HORA_DESCANSO_JORNADA,
       OBSERVACIONES_JORNADA
FROM   JORNADAS;
/

CREATE OR REPLACE VIEW VW_NOMINA AS
SELECT N.ID_NOMINA,
       N.PERIODO_NOMINA,
       N.FECHA_PAGO_NOMINA,
       N.TOTAL_BRUTO_NOMINA,
       N.TOTAL_DESCUENTOS_NOMINA,
       N.TOTAL_NETO_NOMINA,
       N.ESTADO_NOMINA,
       N.ID_SUCURSAL,
       S.NOMBRE_SUCURSAL
FROM   NOMINA     N
JOIN   SUCURSALES S ON S.ID_SUCURSAL = N.ID_SUCURSAL;
/

-- ─────────────────────────────────────────────────────────────
-- INVENTARIO
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_CATEGORIAS_ARTICULO AS
SELECT ID_CATEGORIAS_ARTICULO,
       NOMBRE_CATEGORIA_ARTICULO,
       CODIGO_CATEGORIA_ARTICULO,
       NIVEL_CATEGORIA_ARTICULO,
       ID_CATEGORIA_ARTICULO_PADRE
FROM   CATEGORIAS_ARTICULO;
/

CREATE OR REPLACE VIEW VW_BODEGAS AS
SELECT B.ID_BODEGA,
       B.CODIGO_BODEGA,
       B.NOMBRE_BODEGA,
       B.TIPO_BODEGA,
       B.DIRECCION_BODEGA,
       B.ESTADO_BODEGA,
       B.ID_SUCURSAL,
       S.NOMBRE_SUCURSAL
FROM   BODEGAS    B
JOIN   SUCURSALES S ON S.ID_SUCURSAL = B.ID_SUCURSAL;
/

CREATE OR REPLACE VIEW VW_STOCK_ARTICULO AS
SELECT SA.ID_STOCK_ARTICULO,
       SA.ID_ARTICULO,
       SA.CANTIDAD_DISPONIBLE_STOCK_ARTICULO,
       SA.CANTIDAD_RESERVADA_STOCK_ARTICULO,
       SA.CANTIDAD_TRNASITO_STOCK_ARTICULO,
       SA.COSTO_PROMEDIO_STOCK_ARTICULO,
       SA.ID_UBICACION_BODEGA,
       A.NOMBRE_ARTICULO,
       A.CODIGO_ARTICULO
FROM   STOCK_ARTICULO SA
JOIN   ARTICULO       A ON A.ID_ARTICULO = SA.ID_ARTICULO;
/

-- Vista principal de artículos con categoría, stock y precio activo
-- LATERAL evita ORA-01799 (outer-join no permite subquery en ON clause)
CREATE OR REPLACE VIEW VW_ARTICULOS AS
SELECT A.ID_ARTICULO,
       A.CODIGO_ARTICULO,
       A.CODIGO_BARRA_ARTICULO,
       A.NOMBRE_ARTICULO,
       A.DESCRIPCION_ARTICULO,
       A.TIPO_ARTICULO,
       A.PESO_ARTICULO,
       A.STOCK_MINIMO,
       A.STOCK_MAXIMO,
       A.ESTADO_ARTICULO,
       A.MANEJA_LOTE_ARTICULO,
       A.MANEJA_SERIE_ARTICULO,
       A.ID_CATEGORIA_ARTICULO,
       CA.NOMBRE_CATEGORIA_ARTICULO,
       NVL(SA.CANTIDAD_DISPONIBLE_STOCK_ARTICULO, 0) AS STOCK_DISPONIBLE,
       NVL(SA.COSTO_PROMEDIO_STOCK_ARTICULO, 0)      AS COSTO_PROMEDIO,
       NVL(LP.PRECIO, 0)                             AS PRECIO,
       NVL(LP.DESCUENTO_MAX, 0)                      AS DESCUENTO_MAX
FROM   ARTICULO A
LEFT JOIN CATEGORIAS_ARTICULO CA
       ON CA.ID_CATEGORIAS_ARTICULO = A.ID_CATEGORIA_ARTICULO
LEFT JOIN STOCK_ARTICULO SA
       ON SA.ID_ARTICULO = A.ID_ARTICULO
LEFT JOIN LATERAL (
    SELECT LPD.PRECIO_LISTA_PRECIOS_DET         AS PRECIO,
           LPD.DESCUENTO_MAX_LISTA_PRECIOS_DET  AS DESCUENTO_MAX
    FROM   LISTA_PRECIOS_DET LPD
    WHERE  LPD.ID_ARTICULO = A.ID_ARTICULO
      AND  LPD.ID_LISTA_PRECIOS = (
               SELECT LPH.ID_LISTA_PRECIOS
               FROM   LISTA_PRECIOS LPH
               WHERE  EXISTS (
                          SELECT 1 FROM LISTA_PRECIOS_DET X
                           WHERE X.ID_LISTA_PRECIOS = LPH.ID_LISTA_PRECIOS
                             AND X.ID_ARTICULO = A.ID_ARTICULO)
               ORDER BY CASE
                            WHEN LPH.FECHA_DESDE_LISTA_PRECIOS <= SYSDATE
                             AND (LPH.FECHA_HASTA_LISTA_PRECIOS IS NULL
                                  OR LPH.FECHA_HASTA_LISTA_PRECIOS >= SYSDATE)
                            THEN 0 ELSE 1
                        END,
                        LPH.FECHA_DESDE_LISTA_PRECIOS DESC,
                        LPH.ID_LISTA_PRECIOS DESC
               FETCH FIRST 1 ROW ONLY)
    FETCH FIRST 1 ROW ONLY
) LP ON (1=1);
/

-- ─────────────────────────────────────────────────────────────
-- COMPRAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_PROVEEDORES AS
SELECT P.ID_PROVEEDOR,
       P.CODIGO_PROVEEDOR,
       P.RAZON_SOCIAL_PROVEEDOR,
       P.NIT_PROVEEDOR,
       P.DIRECCION_PROVEEDOR,
       P.TELEFON_PROVEEDOR,
       P.EMAIL_PROVEEDOR,
       P.PLAZO_PAGO_PROVEEDOR,
       P.CLASIFICACION_PROVEEDOR,
       P.ESTADO_PROVEEDOR,
       P.ID_MONEDA,
       M.CODIGO_MONEDA
FROM   PROVEEDORES P
LEFT JOIN MONEDAS  M ON M.ID_MONEDA = P.ID_MONEDA;
/

CREATE OR REPLACE VIEW VW_ORDENES_COMPRA AS
SELECT OC.ID_ORDEN_COMPRA,
       OC.NUMERO_ORDEN_COMPRA,
       OC.FECHA_SOLICITUD_ORDEN_COMPRA,
       OC.FECHA_INGRESO_ORDEN_COMPRA,
       OC.SUBTOTAL_ORDEN_COMPRA,
       OC.IMPUESTO_ORDEN_COMPRA,
       OC.TOTAL_ORDEN_COMPRA,
       OC.ESTADO_ORDEN_COMPRA,
       OC.ID_PROVEEDOR,
       OC.ID_MONEDA,
       OC.ID_SOLICITUD_COMPRA,
       OC.ID_USUARIO_CREA,
       OC.ID_USUARIO_MODIFICA,
       P.RAZON_SOCIAL_PROVEEDOR,
       M.CODIGO_MONEDA
FROM   ORDEN_COMPRA OC
JOIN   PROVEEDORES  P ON P.ID_PROVEEDOR = OC.ID_PROVEEDOR
LEFT JOIN MONEDAS   M ON M.ID_MONEDA    = OC.ID_MONEDA;
/

-- ─────────────────────────────────────────────────────────────
-- VENTAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_CLIENTES AS
SELECT C.ID_CLIENTE,
       C.CODIGO_CLIENTE,
       C.RAZON_SOCIAL_CLIENTE,
       C.NIT_CLIENTE,
       C.LIMITE_CREDITO_CLIENTE,
       C.TELEFON_CLIENTE,
       C.EMAIL_CLIENTE,
       C.PLAZO_PAGO_CLIENTES,
       C.ESTADO_CLIENTE,
       C.ID_LISTA_PRECIOS,
       C.ID_SUCURSAL,
       LP.NOMBRE_LISTA_PRECIOS
FROM   CLIENTE      C
LEFT JOIN LISTA_PRECIOS LP ON LP.ID_LISTA_PRECIOS = C.ID_LISTA_PRECIOS;
/

CREATE OR REPLACE VIEW VW_LISTA_PRECIOS AS
SELECT LP.ID_LISTA_PRECIOS,
       LP.NOMBRE_LISTA_PRECIOS,
       LP.FECHA_DESDE_LISTA_PRECIOS,
       LP.FECHA_HASTA_LISTA_PRECIOS,
       LP.ID_MONEDA,
       M.CODIGO_MONEDA
FROM   LISTA_PRECIOS LP
LEFT JOIN MONEDAS    M ON M.ID_MONEDA = LP.ID_MONEDA;
/

CREATE OR REPLACE VIEW VW_LISTA_PRECIOS_DET AS
SELECT LPD.ID_LISTA_PRECIOS_DET,
       LPD.ID_LISTA_PRECIOS,
       LPD.ID_ARTICULO,
       LPD.PRECIO_LISTA_PRECIOS_DET,
       LPD.DESCUENTO_MAX_LISTA_PRECIOS_DET,
       A.NOMBRE_ARTICULO,
       A.CODIGO_ARTICULO
FROM   LISTA_PRECIOS_DET LPD
JOIN   ARTICULO          A ON A.ID_ARTICULO = LPD.ID_ARTICULO;
/

CREATE OR REPLACE VIEW VW_ORDENES_VENTA AS
SELECT OV.ID_ORDEN_VENTA,
       OV.NUMERO_ORDEN_VENTA,
       OV.FECHA_SOLICITUD_ORDEN_VENTA,
       OV.FECHA_ENTREGA_ORDEN_VENTA,
       OV.SUBTOTAL_ORDEN_VENTA,
       OV.DESCUENTO_ORDEN_VENTA,
       OV.IMPUESTO_ORDEN_VENTA,
       OV.TOTAL_ORDEN_VENTA,
       OV.ESTADO_ORDEN_VENTA,
       OV.ID_CLIENTE,
       OV.ID_USUARIO_CREA,
       OV.ID_USUARIO_MODIFICA,
       C.RAZON_SOCIAL_CLIENTE,
       C.NIT_CLIENTE
FROM   ORDEN_VENTA OV
LEFT JOIN CLIENTE  C ON C.ID_CLIENTE = OV.ID_CLIENTE;
/

CREATE OR REPLACE VIEW VW_ORDEN_VENTA_DETALLE AS
SELECT OVD.ID_ORDEN_VENTA_DETALLE,
       OVD.ID_ORDEN_VENTA,
       OVD.ID_ARTICULO,
       OVD.CANTIDAD_SOLICITUD_VENTA_COMPRA_DETALLE   AS CANTIDAD,
       OVD.CANTIDAD_ENTREGADA_VENTA_COMPRA_DETALLE,
       OVD.PRECIO_UNITARIO_ORDEN_VENTA_DETALLE       AS PRECIO_UNITARIO,
       OVD.SUBTOTAL_ORDEN_VENTA_DETALLE              AS SUBTOTAL,
       OVD.ESTADO_ORDEN_VENTA_DETALLE,
       A.CODIGO_ARTICULO,
       A.NOMBRE_ARTICULO
FROM   ORDEN_VENTA_DETALLE OVD
JOIN   ARTICULO             A ON A.ID_ARTICULO = OVD.ID_ARTICULO;
/

CREATE OR REPLACE VIEW VW_FACTURAS_VENTA AS
SELECT FV.ID_FACTURA_VENTA,
       FV.SERIE_FACTURA_VENTA,
       FV.CORRELATIVO_FACTURA_VENTA,
       FV.FECHA_SALIDA_FACTURA_VENTA,
       FV.FECHA_FACTURA_VENTA,
       FV.ESTADO_SALIDA_MERCADERIA,
       FV.TOTAL_FACTURA_VENTA,
       FV.ID_SALIDA_MERCADERIA,
       FV.ID_USUARIO_CREA,
       SM.NUMERO_SALIDA_MERCADERIA
FROM   FACTURA_VENTA    FV
LEFT JOIN SALIDA_MERCADERIA SM ON SM.ID_SALIDA_MERCADERIA = FV.ID_SALIDA_MERCADERIA;
/

CREATE OR REPLACE VIEW VW_DEVOLUCIONES_VENTA AS
SELECT DV.ID_DEVOLUCION_VENTA,
       DV.NUMERO_DEVOLUCION,
       DV.MOTIVO_DEVOLUCION,
       DV.FECHA_DEVOLUCION_VENTA,
       DV.TOTAL_DEVOLUCION_VENTA,
       DV.OBSERVACION_DEVOLUCION_VENTA,
       DV.ESTADO_DEVOLUCION_VENTA,
       DV.ID_SALIDA_MERCADERIA,
       SM.NUMERO_SALIDA_MERCADERIA
FROM   DEVOLUCION_VENTA      DV
LEFT JOIN SALIDA_MERCADERIA SM ON SM.ID_SALIDA_MERCADERIA = DV.ID_SALIDA_MERCADERIA;
/

-- ─────────────────────────────────────────────────────────────
-- PRODUCCIÓN
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_CENTROS_TRABAJO AS
SELECT CT.ID_CENTRO_TRABAJO,
       CT.CODIGO_CENTRO_TRABAJO,
       CT.NOMBRE_CENTRO_TRABAJO,
       CT.CAPACIDAD_HORA,
       CT.VOSTO_HORA_CENTRO_TRABAJO,
       CT.ESTADO_CENTRO_TRABAJO,
       CT.ID_SUCURSAL,
       S.NOMBRE_SUCURSAL
FROM   CENTRO_TRABAJO CT
LEFT JOIN SUCURSALES  S ON S.ID_SUCURSAL = CT.ID_SUCURSAL;
/

CREATE OR REPLACE VIEW VW_ORDENES_PRODUCCION AS
SELECT OP.ID_ORDEN_PRODUCCION,
       OP.CODIGO_ORDEN_PRODUCCION,
       OP.FECHA_IN_ORDEN_PRODUCCION,
       OP.FECHA_FIN_ORDEN_PRODUCCION,
       OP.CANTIDAD_PLANIFICADA_ORDEN_PRODUCCION,
       OP.CANTIDAD_PRODUCIDA_ORIDEN_PRODUCCION,
       OP.CANTIDAD_MERMA_ORDEN_PRODUCCION,
       OP.ESTADO_ORDEN_PRODUCCION,
       OP.ID_LISTA_MATERIALES,
       OP.ID_CENTRO_TRABAJO,
       OP.ID_SUCURSAL,
       OP.ID_USUARIO_CREA,
       OP.ID_USUARIO_MODIFICA,
       CT.NOMBRE_CENTRO_TRABAJO,
       LM.NOMBRE_LISTA__MATERIALES
FROM   ORDEN_PRODUCCION OP
LEFT JOIN CENTRO_TRABAJO   CT ON CT.ID_CENTRO_TRABAJO   = OP.ID_CENTRO_TRABAJO
LEFT JOIN LISTA_MATERIALES LM ON LM.ID_LISTA_MATERIALES = OP.ID_LISTA_MATERIALES;
/

-- ─────────────────────────────────────────────────────────────
-- LOGÍSTICA / TRANSPORTE
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW VW_VEHICULOS AS
SELECT V.ID_VEHICULO,
       V.PLACA_VEHICULO,
       V.MARCA_VEHICULO,
       V.MODELO_VEHICULO,
       V.TIPO_VEHICULO,
       V.CAPACIDAD_KG_VEHICULO,
       V.KM_ULT_SERV_VEHICULO,
       V.KM_SIG_SERV_VEHICULO,
       V.ESTADO_VEHICULO,
       V.ID_SUCURSAL,
       S.NOMBRE_SUCURSAL
FROM   VEHICULO   V
LEFT JOIN SUCURSALES S ON S.ID_SUCURSAL = V.ID_SUCURSAL;
/

CREATE OR REPLACE VIEW VW_TRANSPORTISTAS AS
SELECT T.ID_TRANSPORTISTA,
       T.NOMBRE_TRANSPORTISTA,
       T.APELLIDOS_TRANSPORTISTA,
       T.LICENCIA_TRANSPORTISTA,
       T.DPI_TRANPORTISTA,
       T.TIPO_LIC_TRANSPORTISTA,
       T.ESTADO_TRANSPORTISTA,
       T.ID_EMPLEADO,
       E.NOMBRES_EMPLEADO
FROM   TRANSPORTISTA T
LEFT JOIN EMPLEADOS  E ON E.ID_EMPLEADO = T.ID_EMPLEADO;
/

CREATE OR REPLACE VIEW VW_ORDENES_DESPACHO AS
SELECT OD.ID_ORDEN_DESPACHO,
       OD.NOMBRE_ORDEN_DESPACHO,
       OD.FECHA_CREA_ORDEN_DESPACHO,
       OD.FECHA_ENTREGA_ORDEN_DESPACHO,
       OD.PESO_KG_TOTAL_ORDEN_DESPACHO,
       OD.ESTADO_ORDEN_DESPACHADO,
       OD.ID_VEHICULO,
       OD.ID_TRANSPORTISTA,
       OD.ID_SUCURSAL,
       V.PLACA_VEHICULO,
       T.NOMBRE_TRANSPORTISTA,
       T.APELLIDOS_TRANSPORTISTA
FROM   ORDEN_DESPACHADO OD
LEFT JOIN VEHICULO       V ON V.ID_VEHICULO      = OD.ID_VEHICULO
LEFT JOIN TRANSPORTISTA  T ON T.ID_TRANSPORTISTA = OD.ID_TRANSPORTISTA;
/

CREATE OR REPLACE VIEW VW_ENTREGAS AS
SELECT E.ID_ENTREGA,
       E.FECHA_ENTREGA,
       E.NOMBRE_RECIBE_ENTREGA,
       E.APELLIDAS_RECIBE_ENTREGA,
       E.DPL_RECIBRE_ENTREGA,
       E.FIRMA_RECIBE_ENTREGA,
       E.FOTO_ENTREGA,
       E."OBSERVACIÓN_ENTREGA",
       E.UBICACION_ENTREGA,
       E.ID_DESPACHO_DETALLE,
       OD.NOMBRE_ORDEN_DESPACHO
FROM   ENTREGA          E
LEFT JOIN ORDEN_DESPACHADO OD ON OD.ID_ORDEN_DESPACHO = E.ID_DESPACHO_DETALLE;
/

-- ─────────────────────────────────────────────────────────────
-- DASHBOARD
-- ─────────────────────────────────────────────────────────────

-- Estadísticas generales (una fila)
CREATE OR REPLACE VIEW VW_DASHBOARD_STATS AS
SELECT (SELECT COUNT(*) FROM ARTICULO      WHERE ESTADO_ARTICULO       = 'A')          AS ARTICULOS_ACTIVOS,
       (SELECT COUNT(*) FROM ORDEN_VENTA   WHERE ESTADO_ORDEN_VENTA    IN ('P', 'E'))   AS ORDENES_PENDIENTES,
       (SELECT COUNT(*) FROM CLIENTE       WHERE ESTADO_CLIENTE        = 'A')           AS CLIENTES_ACTIVOS,
       (SELECT COUNT(*) FROM ORDEN_DESPACHADO WHERE ESTADO_ORDEN_DESPACHADO IN ('P','E')) AS DESPACHOS_EN_RUTA
FROM   DUAL;
/

-- Resumen de ventas del mes en curso (una fila)
CREATE OR REPLACE VIEW VW_DASHBOARD_VENTAS_MES AS
SELECT COUNT(*)                                                        AS TOTAL_ORDENES,
       SUM(TOTAL_ORDEN_VENTA)                                          AS TOTAL_VENTAS,
       AVG(TOTAL_ORDEN_VENTA)                                          AS PROMEDIO_VENTA,
       COUNT(CASE WHEN ESTADO_ORDEN_VENTA = 'P' THEN 1 END)           AS ORDENES_PENDIENTES,
       COUNT(CASE WHEN ESTADO_ORDEN_VENTA = 'E' THEN 1 END)           AS ORDENES_PROCESO,
       COUNT(CASE WHEN ESTADO_ORDEN_VENTA = 'C' THEN 1 END)           AS ORDENES_COMPLETADAS
FROM   ORDEN_VENTA
WHERE  TRUNC(FECHA_SOLICITUD_ORDEN_VENTA) >= TRUNC(SYSDATE, 'MM');
/

-- Top productos del mes por cantidad vendida
CREATE OR REPLACE VIEW VW_DASHBOARD_TOP_PRODUCTOS AS
SELECT A.CODIGO_ARTICULO,
       A.NOMBRE_ARTICULO,
       SUM(OVD.CANTIDAD_SOLICITUD_VENTA_COMPRA_DETALLE) AS CANTIDAD_VENDIDA,
       SUM(OVD.SUBTOTAL_ORDEN_VENTA_DETALLE)            AS TOTAL_VENDIDO
FROM   ORDEN_VENTA_DETALLE OVD
JOIN   ARTICULO             A  ON A.ID_ARTICULO    = OVD.ID_ARTICULO
JOIN   ORDEN_VENTA          OV ON OV.ID_ORDEN_VENTA = OVD.ID_ORDEN_VENTA
WHERE  TRUNC(OV.FECHA_SOLICITUD_ORDEN_VENTA) >= TRUNC(SYSDATE, 'MM')
GROUP BY A.CODIGO_ARTICULO, A.NOMBRE_ARTICULO;
/

-- Ventas completadas por mes (últimos 6 meses)
CREATE OR REPLACE VIEW VW_DASHBOARD_VENTAS_POR_MES AS
SELECT TO_CHAR(FECHA_SOLICITUD_ORDEN_VENTA, 'YYYY-MM') AS MES,
       SUM(TOTAL_ORDEN_VENTA)                          AS TOTAL
FROM   ORDEN_VENTA
WHERE  FECHA_SOLICITUD_ORDEN_VENTA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)
  AND  ESTADO_ORDEN_VENTA = 'C'
GROUP BY TO_CHAR(FECHA_SOLICITUD_ORDEN_VENTA, 'YYYY-MM');
/

-- Artículos con stock bajo (≤ 1.5× stock mínimo)
CREATE OR REPLACE VIEW VW_DASHBOARD_STOCK_BAJO AS
SELECT A.CODIGO_ARTICULO,
       A.NOMBRE_ARTICULO,
       NVL(SA.CANTIDAD_DISPONIBLE_STOCK_ARTICULO, 0)  AS STOCK_ACTUAL,
       A.STOCK_MINIMO,
       CASE
           WHEN NVL(SA.CANTIDAD_DISPONIBLE_STOCK_ARTICULO, 0) <= A.STOCK_MINIMO       THEN 'CRITICO'
           WHEN NVL(SA.CANTIDAD_DISPONIBLE_STOCK_ARTICULO, 0) <= A.STOCK_MINIMO * 1.5 THEN 'BAJO'
           ELSE 'OK'
       END AS ESTADO
FROM   ARTICULO A
LEFT JOIN STOCK_ARTICULO SA ON SA.ID_ARTICULO = A.ID_ARTICULO
WHERE  A.ESTADO_ARTICULO = 'A'
  AND  NVL(SA.CANTIDAD_DISPONIBLE_STOCK_ARTICULO, 0) <= A.STOCK_MINIMO * 1.5;
/

-- Órdenes de compra pendientes (una fila de contadores)
CREATE OR REPLACE VIEW VW_DASHBOARD_OC_PENDIENTES AS
SELECT COUNT(*)                                                           AS TOTAL_PENDIENTES,
       COUNT(CASE WHEN ESTADO_ORDEN_COMPRA = 'P' THEN 1 END)             AS ORDENES_PENDIENTES,
       COUNT(CASE WHEN ESTADO_ORDEN_COMPRA = 'E' THEN 1 END)             AS ORDENES_PROCESO
FROM   ORDEN_COMPRA
WHERE  ESTADO_ORDEN_COMPRA IN ('P', 'E');
/

-- Clientes nuevos del mes con compras
CREATE OR REPLACE VIEW VW_DASHBOARD_CLIENTES_NUEVOS AS
SELECT COUNT(DISTINCT C.ID_CLIENTE)                                                          AS TOTAL_NUEVOS,
       COUNT(DISTINCT CASE WHEN OV.ESTADO_ORDEN_VENTA = 'C' THEN OV.ID_CLIENTE END)         AS CLIENTES_CON_COMPRAS
FROM   CLIENTE     C
LEFT JOIN ORDEN_VENTA OV ON OV.ID_CLIENTE = C.ID_CLIENTE
WHERE  C.ESTADO_CLIENTE = 'A'
  AND  C.ID_CLIENTE IN (
           SELECT ID_CLIENTE FROM ORDEN_VENTA
            WHERE TRUNC(FECHA_SOLICITUD_ORDEN_VENTA) >= TRUNC(SYSDATE, 'MM'));
/

-- Inventario agrupado por categoría
CREATE OR REPLACE VIEW VW_DASHBOARD_INV_CATEGORIA AS
SELECT CA.NOMBRE_CATEGORIA_ARTICULO                        AS CATEGORIA,
       COUNT(A.ID_ARTICULO)                                AS TOTAL_ARTICULOS,
       SUM(NVL(SA.CANTIDAD_DISPONIBLE_STOCK_ARTICULO, 0))  AS CANTIDAD_TOTAL
FROM   ARTICULO A
LEFT JOIN CATEGORIAS_ARTICULO CA ON CA.ID_CATEGORIAS_ARTICULO = A.ID_CATEGORIA_ARTICULO
LEFT JOIN STOCK_ARTICULO      SA ON SA.ID_ARTICULO             = A.ID_ARTICULO
WHERE  A.ESTADO_ARTICULO = 'A'
GROUP BY CA.NOMBRE_CATEGORIA_ARTICULO;
/

-- Estado de despachos del mes
CREATE OR REPLACE VIEW VW_DASHBOARD_ESTADO_DESPACHOS AS
SELECT COUNT(*)                                                                  AS TOTAL_DESPACHOS,
       COUNT(CASE WHEN ESTADO_ORDEN_DESPACHADO = 'P' THEN 1 END)                AS PENDIENTES,
       COUNT(CASE WHEN ESTADO_ORDEN_DESPACHADO = 'E' THEN 1 END)                AS EN_PROGRESO,
       COUNT(CASE WHEN ESTADO_ORDEN_DESPACHADO = 'C' THEN 1 END)                AS COMPLETADOS
FROM   ORDEN_DESPACHADO
WHERE  TRUNC(FECHA_CREA_ORDEN_DESPACHO) >= TRUNC(SYSDATE, 'MM');
/
