-- =============================================================
-- PROCEDIMIENTOS ALMACENADOS - Muebleria Oracle 21c
-- Todos los INSERT, UPDATE y DELETE del sistema se ejecutan
-- a través de estos procedimientos.
-- Convención: SP_<ENTIDAD>_<ACCION>
--   Acciones: INS (INSERT), UPD (UPDATE), DEL (DELETE/lógico)
-- Ejecutar como usuario: Muebleria
-- =============================================================

-- ─────────────────────────────────────────────────────────────
-- AUTENTICACIÓN / USUARIOS
-- ─────────────────────────────────────────────────────────────

-- Actualiza la fecha de último acceso al hacer login
CREATE OR REPLACE PROCEDURE SP_USR_UPD_ACCESO(
    p_id_usuario IN USUARIOS.ID_USUARIO%TYPE
) AS
BEGIN
    UPDATE USUARIOS
       SET ULTIMO_ACCESO_USUARIO = SYSTIMESTAMP
     WHERE ID_USUARIO = p_id_usuario;
END SP_USR_UPD_ACCESO;
/

-- Inserta un CLIENTE durante el proceso de registro
CREATE OR REPLACE PROCEDURE SP_REG_INS_CLIENTE(
    p_cod    IN CLIENTE.CODIGO_CLIENTE%TYPE,
    p_nom    IN CLIENTE.RAZON_SOCIAL_CLIENTE%TYPE,
    p_nit    IN CLIENTE.NIT_CLIENTE%TYPE,
    p_tel    IN CLIENTE.TELEFON_CLIENTE%TYPE,
    p_email  IN CLIENTE.EMAIL_CLIENTE%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO CLIENTE(CODIGO_CLIENTE, RAZON_SOCIAL_CLIENTE, NIT_CLIENTE,
                        TELEFON_CLIENTE, EMAIL_CLIENTE, ESTADO_CLIENTE)
    VALUES (p_cod, p_nom, p_nit, p_tel, p_email, 'A')
    RETURNING ID_CLIENTE INTO p_id_out;
END SP_REG_INS_CLIENTE;
/

-- Inserta un USUARIO durante el proceso de registro
CREATE OR REPLACE PROCEDURE SP_REG_INS_USUARIO(
    p_user   IN USUARIOS.USERNAME_USUARIO%TYPE,
    p_pass   IN USUARIOS.PASSWORD_USUARIO%TYPE,
    p_email  IN USUARIOS.EMAIL_USUARIO%TYPE,
    p_rol    IN USUARIOS.ID_ROL%TYPE,
    p_suc    IN USUARIOS.ID_SUCURSAL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO USUARIOS(USERNAME_USUARIO, PASSWORD_USUARIO, EMAIL_USUARIO,
                         ESTADO_USUARIO, ID_ROL, ID_SUCURSAL)
    VALUES (p_user, p_pass, p_email, 'A', p_rol, p_suc)
    RETURNING ID_USUARIO INTO p_id_out;
END SP_REG_INS_USUARIO;
/

-- ─────────────────────────────────────────────────────────────
-- EMPRESAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_EMP_INS(
    p_nm   IN EMPRESAS.NOMBRE_EMPRESA%TYPE,
    p_nit  IN EMPRESAS.NIT_EMPRESA%TYPE,
    p_rs   IN EMPRESAS.RAZON_SOCIAL_EMPRESA%TYPE,
    p_dir  IN EMPRESAS.DIRECCION_EMPRESA%TYPE,
    p_logo IN EMPRESAS.LOGO_EMPRESA%TYPE,
    p_est  IN EMPRESAS.ESTADO_EMPRESA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO EMPRESAS(NOMBRE_EMPRESA, NIT_EMPRESA, RAZON_SOCIAL_EMPRESA,
                         DIRECCION_EMPRESA, LOGO_EMPRESA, ESTADO_EMPRESA)
    VALUES (p_nm, p_nit, p_rs, p_dir, p_logo, NVL(p_est, 'A'))
    RETURNING ID_EMPRESA INTO p_id_out;
END SP_EMP_INS;
/

CREATE OR REPLACE PROCEDURE SP_EMP_UPD(
    p_nm  IN EMPRESAS.NOMBRE_EMPRESA%TYPE,
    p_dir IN EMPRESAS.DIRECCION_EMPRESA%TYPE,
    p_est IN EMPRESAS.ESTADO_EMPRESA%TYPE,
    p_id  IN EMPRESAS.ID_EMPRESA%TYPE
) AS
BEGIN
    UPDATE EMPRESAS
       SET NOMBRE_EMPRESA    = NVL(p_nm,  NOMBRE_EMPRESA),
           DIRECCION_EMPRESA = NVL(p_dir, DIRECCION_EMPRESA),
           ESTADO_EMPRESA    = NVL(p_est, ESTADO_EMPRESA)
     WHERE ID_EMPRESA = p_id;
END SP_EMP_UPD;
/

CREATE OR REPLACE PROCEDURE SP_EMP_DEL(
    p_id IN EMPRESAS.ID_EMPRESA%TYPE
) AS
BEGIN
    UPDATE EMPRESAS SET ESTADO_EMPRESA = 'I' WHERE ID_EMPRESA = p_id;
END SP_EMP_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- SUCURSALES
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_SUC_INS(
    p_c   IN SUCURSALES.CODIGO_SUCURSAL%TYPE,
    p_n   IN SUCURSALES.NOMBRE_SUCURSAL%TYPE,
    p_dir IN SUCURSALES.DIRECCION_SUCURSAL%TYPE,
    p_e   IN SUCURSALES.EMAIL_SUCURSAL%TYPE,
    p_est IN SUCURSALES.ESTADO_SUCURSAL%TYPE,
    p_emp IN SUCURSALES.ID_EMPRESA%TYPE,
    p_mun IN SUCURSALES.ID_MUNICIPIO%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO SUCURSALES(CODIGO_SUCURSAL, NOMBRE_SUCURSAL, DIRECCION_SUCURSAL,
                           EMAIL_SUCURSAL, ESTADO_SUCURSAL, ID_EMPRESA, ID_MUNICIPIO)
    VALUES (p_c, p_n, p_dir, p_e, NVL(p_est, 'A'), p_emp, p_mun)
    RETURNING ID_SUCURSAL INTO p_id_out;
END SP_SUC_INS;
/

CREATE OR REPLACE PROCEDURE SP_SUC_UPD(
    p_n   IN SUCURSALES.NOMBRE_SUCURSAL%TYPE,
    p_est IN SUCURSALES.ESTADO_SUCURSAL%TYPE,
    p_id  IN SUCURSALES.ID_SUCURSAL%TYPE
) AS
BEGIN
    UPDATE SUCURSALES
       SET NOMBRE_SUCURSAL  = NVL(p_n,   NOMBRE_SUCURSAL),
           ESTADO_SUCURSAL  = NVL(p_est, ESTADO_SUCURSAL)
     WHERE ID_SUCURSAL = p_id;
END SP_SUC_UPD;
/

CREATE OR REPLACE PROCEDURE SP_SUC_DEL(
    p_id IN SUCURSALES.ID_SUCURSAL%TYPE
) AS
BEGIN
    UPDATE SUCURSALES SET ESTADO_SUCURSAL = 'I' WHERE ID_SUCURSAL = p_id;
END SP_SUC_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- ROLES
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_ROL_INS(
    p_n   IN ROLES.NOMBRE_ROL%TYPE,
    p_d   IN ROLES.DESCRIPCION_ROL%TYPE,
    p_r   IN ROLES.RANGO_ROL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO ROLES(NOMBRE_ROL, DESCRIPCION_ROL, RANGO_ROL)
    VALUES (p_n, p_d, p_r)
    RETURNING ID_ROL INTO p_id_out;
END SP_ROL_INS;
/

CREATE OR REPLACE PROCEDURE SP_ROL_UPD(
    p_n  IN ROLES.NOMBRE_ROL%TYPE,
    p_d  IN ROLES.DESCRIPCION_ROL%TYPE,
    p_r  IN ROLES.RANGO_ROL%TYPE,
    p_id IN ROLES.ID_ROL%TYPE
) AS
BEGIN
    UPDATE ROLES
       SET NOMBRE_ROL      = NVL(p_n, NOMBRE_ROL),
           DESCRIPCION_ROL = NVL(p_d, DESCRIPCION_ROL),
           RANGO_ROL       = NVL(p_r, RANGO_ROL)
     WHERE ID_ROL = p_id;
END SP_ROL_UPD;
/

CREATE OR REPLACE PROCEDURE SP_ROL_DEL(
    p_id IN ROLES.ID_ROL%TYPE
) AS
BEGIN
    DELETE FROM ROLES WHERE ID_ROL = p_id;
END SP_ROL_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- USUARIOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_USR_INS(
    p_u   IN USUARIOS.USERNAME_USUARIO%TYPE,
    p_p   IN USUARIOS.PASSWORD_USUARIO%TYPE,
    p_e   IN USUARIOS.EMAIL_USUARIO%TYPE,
    p_est IN USUARIOS.ESTADO_USUARIO%TYPE,
    p_r   IN USUARIOS.ID_ROL%TYPE,
    p_s   IN USUARIOS.ID_SUCURSAL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO USUARIOS(USERNAME_USUARIO, PASSWORD_USUARIO, EMAIL_USUARIO,
                         ESTADO_USUARIO, ID_ROL, ID_SUCURSAL)
    VALUES (p_u, p_p, p_e, NVL(p_est, 'A'), p_r, p_s)
    RETURNING ID_USUARIO INTO p_id_out;
END SP_USR_INS;
/

CREATE OR REPLACE PROCEDURE SP_USR_UPD(
    p_e   IN USUARIOS.EMAIL_USUARIO%TYPE,
    p_est IN USUARIOS.ESTADO_USUARIO%TYPE,
    p_r   IN USUARIOS.ID_ROL%TYPE,
    p_p   IN USUARIOS.PASSWORD_USUARIO%TYPE,
    p_id  IN USUARIOS.ID_USUARIO%TYPE
) AS
BEGIN
    UPDATE USUARIOS
       SET EMAIL_USUARIO    = NVL(p_e,   EMAIL_USUARIO),
           ESTADO_USUARIO   = NVL(p_est, ESTADO_USUARIO),
           ID_ROL           = NVL(p_r,   ID_ROL),
           PASSWORD_USUARIO = NVL(p_p,   PASSWORD_USUARIO)
     WHERE ID_USUARIO = p_id;
END SP_USR_UPD;
/

CREATE OR REPLACE PROCEDURE SP_USR_DEL(
    p_id IN USUARIOS.ID_USUARIO%TYPE
) AS
BEGIN
    UPDATE USUARIOS SET ESTADO_USUARIO = 'I' WHERE ID_USUARIO = p_id;
END SP_USR_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- PERMISOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_PERM_INS(
    p_n   IN PERMISOS.NOMBRE_PERMISO%TYPE,
    p_d   IN PERMISOS.DESCRIPCION_PERMISO%TYPE,
    p_m   IN PERMISOS.MODULO_PERMISO%TYPE,
    p_est IN PERMISOS.ESTADO%TYPE,
    p_r   IN PERMISOS.ID_ROL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO PERMISOS(NOMBRE_PERMISO, DESCRIPCION_PERMISO, MODULO_PERMISO, ESTADO, ID_ROL)
    VALUES (p_n, p_d, p_m, NVL(p_est, 'A'), p_r)
    RETURNING ID_PERMISO INTO p_id_out;
END SP_PERM_INS;
/

CREATE OR REPLACE PROCEDURE SP_PERM_UPD(
    p_est IN PERMISOS.ESTADO%TYPE,
    p_m   IN PERMISOS.MODULO_PERMISO%TYPE,
    p_id  IN PERMISOS.ID_PERMISO%TYPE
) AS
BEGIN
    UPDATE PERMISOS
       SET ESTADO         = NVL(p_est, ESTADO),
           MODULO_PERMISO = NVL(p_m,   MODULO_PERMISO)
     WHERE ID_PERMISO = p_id;
END SP_PERM_UPD;
/

CREATE OR REPLACE PROCEDURE SP_PERM_DEL(
    p_id IN PERMISOS.ID_PERMISO%TYPE
) AS
BEGIN
    DELETE FROM PERMISOS WHERE ID_PERMISO = p_id;
END SP_PERM_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- MONEDAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_MON_INS(
    p_c  IN MONEDAS.CODIGO_MONEDA%TYPE,
    p_n  IN MONEDAS.NOMBRE_MONEDA%TYPE,
    p_s  IN MONEDAS.SIMBOLO_MONEDA%TYPE,
    p_d  IN MONEDAS.DECIMALES_MONEDA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO MONEDAS(CODIGO_MONEDA, NOMBRE_MONEDA, SIMBOLO_MONEDA, DECIMALES_MONEDA)
    VALUES (p_c, p_n, p_s, NVL(p_d, 2))
    RETURNING ID_MONEDA INTO p_id_out;
END SP_MON_INS;
/

CREATE OR REPLACE PROCEDURE SP_MON_UPD(
    p_n  IN MONEDAS.NOMBRE_MONEDA%TYPE,
    p_id IN MONEDAS.ID_MONEDA%TYPE
) AS
BEGIN
    UPDATE MONEDAS SET NOMBRE_MONEDA = NVL(p_n, NOMBRE_MONEDA) WHERE ID_MONEDA = p_id;
END SP_MON_UPD;
/

CREATE OR REPLACE PROCEDURE SP_MON_DEL(
    p_id IN MONEDAS.ID_MONEDA%TYPE
) AS
BEGIN
    DELETE FROM MONEDAS WHERE ID_MONEDA = p_id;
END SP_MON_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- DEPARTAMENTOS GEOGRÁFICOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_DEPT_INS(
    p_n  IN DEPARTAMENTO.NOMBRE_DEPARTAMENTO%TYPE,
    p_f  IN DEPARTAMENTO.FRECUENCIA_DEPARTAMENTO%TYPE,
    p_z  IN DEPARTAMENTO.ZONA_TERRITORIAL_DEPARTAMENTO%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO DEPARTAMENTO(NOMBRE_DEPARTAMENTO, FRECUENCIA_DEPARTAMENTO, ZONA_TERRITORIAL_DEPARTAMENTO)
    VALUES (p_n, p_f, p_z)
    RETURNING ID_DEPARTAMENTO INTO p_id_out;
END SP_DEPT_INS;
/

CREATE OR REPLACE PROCEDURE SP_DEPT_UPD(
    p_n  IN DEPARTAMENTO.NOMBRE_DEPARTAMENTO%TYPE,
    p_id IN DEPARTAMENTO.ID_DEPARTAMENTO%TYPE
) AS
BEGIN
    UPDATE DEPARTAMENTO
       SET NOMBRE_DEPARTAMENTO = NVL(p_n, NOMBRE_DEPARTAMENTO)
     WHERE ID_DEPARTAMENTO = p_id;
END SP_DEPT_UPD;
/

CREATE OR REPLACE PROCEDURE SP_DEPT_DEL(
    p_id IN DEPARTAMENTO.ID_DEPARTAMENTO%TYPE
) AS
BEGIN
    DELETE FROM DEPARTAMENTO WHERE ID_DEPARTAMENTO = p_id;
END SP_DEPT_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- MUNICIPIOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_MUN_INS(
    p_n   IN MUNICIPIOS.NOMBRE_MUNICIPIO%TYPE,
    p_cp  IN MUNICIPIOS.CODIGO_POSTAL_MUNICIPIO%TYPE,
    p_dep IN MUNICIPIOS.ID_DEPARTAMENTO%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO MUNICIPIOS(NOMBRE_MUNICIPIO, CODIGO_POSTAL_MUNICIPIO, ID_DEPARTAMENTO)
    VALUES (p_n, p_cp, p_dep)
    RETURNING ID_MUNICIPIO INTO p_id_out;
END SP_MUN_INS;
/

CREATE OR REPLACE PROCEDURE SP_MUN_DEL(
    p_id IN MUNICIPIOS.ID_MUNICIPIO%TYPE
) AS
BEGIN
    DELETE FROM MUNICIPIOS WHERE ID_MUNICIPIO = p_id;
END SP_MUN_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- RRHH - DEPARTAMENTOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_DEPRRHH_INS(
    p_n     IN DEPARTAMENTO_RRHH.NOMBRE_DEPARTAMENTO_RRHH%TYPE,
    p_c     IN DEPARTAMENTO_RRHH.CODIGO_DEPARTAMENTO_RRHH%TYPE,
    p_s     IN DEPARTAMENTO_RRHH.ID_SUCURSAL%TYPE,
    p_padre IN DEPARTAMENTO_RRHH.ID_DEPARTAMENTO_RRHH_PADRE%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO DEPARTAMENTO_RRHH(NOMBRE_DEPARTAMENTO_RRHH, CODIGO_DEPARTAMENTO_RRHH,
                                   ID_SUCURSAL, ID_DEPARTAMENTO_RRHH_PADRE)
    VALUES (p_n, p_c, p_s, p_padre)
    RETURNING ID_DEPARTAMENTO_RRHH INTO p_id_out;
END SP_DEPRRHH_INS;
/

CREATE OR REPLACE PROCEDURE SP_DEPRRHH_UPD(
    p_n  IN DEPARTAMENTO_RRHH.NOMBRE_DEPARTAMENTO_RRHH%TYPE,
    p_id IN DEPARTAMENTO_RRHH.ID_DEPARTAMENTO_RRHH%TYPE
) AS
BEGIN
    UPDATE DEPARTAMENTO_RRHH
       SET NOMBRE_DEPARTAMENTO_RRHH = NVL(p_n, NOMBRE_DEPARTAMENTO_RRHH)
     WHERE ID_DEPARTAMENTO_RRHH = p_id;
END SP_DEPRRHH_UPD;
/

CREATE OR REPLACE PROCEDURE SP_DEPRRHH_DEL(
    p_id IN DEPARTAMENTO_RRHH.ID_DEPARTAMENTO_RRHH%TYPE
) AS
BEGIN
    DELETE FROM DEPARTAMENTO_RRHH WHERE ID_DEPARTAMENTO_RRHH = p_id;
END SP_DEPRRHH_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- RRHH - CARGOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_CARRRHH_INS(
    p_n    IN CARGO_RRHH.NOMBRE_CARGO_RRHH%TYPE,
    p_niv  IN CARGO_RRHH.NIVEL_CARGO_RRHH%TYPE,
    p_smin IN CARGO_RRHH.SALARIO_MIN_CARGO_RRHH%TYPE,
    p_smax IN CARGO_RRHH.SALARIO_MAX_CARGO_RRHH%TYPE,
    p_dep  IN CARGO_RRHH.ID_DEPARTAMENTO_RRHH%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO CARGO_RRHH(NOMBRE_CARGO_RRHH, NIVEL_CARGO_RRHH,
                            SALARIO_MIN_CARGO_RRHH, SALARIO_MAX_CARGO_RRHH, ID_DEPARTAMENTO_RRHH)
    VALUES (p_n, p_niv, p_smin, p_smax, p_dep)
    RETURNING ID_CARGO_RRHH INTO p_id_out;
END SP_CARRRHH_INS;
/

CREATE OR REPLACE PROCEDURE SP_CARRRHH_UPD(
    p_n    IN CARGO_RRHH.NOMBRE_CARGO_RRHH%TYPE,
    p_niv  IN CARGO_RRHH.NIVEL_CARGO_RRHH%TYPE,
    p_smin IN CARGO_RRHH.SALARIO_MIN_CARGO_RRHH%TYPE,
    p_smax IN CARGO_RRHH.SALARIO_MAX_CARGO_RRHH%TYPE,
    p_id   IN CARGO_RRHH.ID_CARGO_RRHH%TYPE
) AS
BEGIN
    UPDATE CARGO_RRHH
       SET NOMBRE_CARGO_RRHH      = NVL(p_n,    NOMBRE_CARGO_RRHH),
           NIVEL_CARGO_RRHH       = NVL(p_niv,  NIVEL_CARGO_RRHH),
           SALARIO_MIN_CARGO_RRHH = NVL(p_smin, SALARIO_MIN_CARGO_RRHH),
           SALARIO_MAX_CARGO_RRHH = NVL(p_smax, SALARIO_MAX_CARGO_RRHH)
     WHERE ID_CARGO_RRHH = p_id;
END SP_CARRRHH_UPD;
/

CREATE OR REPLACE PROCEDURE SP_CARRRHH_DEL(
    p_id IN CARGO_RRHH.ID_CARGO_RRHH%TYPE
) AS
BEGIN
    DELETE FROM CARGO_RRHH WHERE ID_CARGO_RRHH = p_id;
END SP_CARRRHH_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- EMPLEADOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_EMPL_INS(
    p_num   IN EMPLEADOS.NUMERO_EMPLEADO%TYPE,
    p_dpi   IN EMPLEADOS.DPI_EMPLEADO%TYPE,
    p_nom   IN EMPLEADOS.NOMBRES_EMPLEADO%TYPE,
    p_ape   IN EMPLEADOS.APELLIDOS_EMPLEADO%TYPE,
    p_fn    IN VARCHAR2,
    p_gen   IN EMPLEADOS.GENERO_EMPLEADO%TYPE,
    p_email IN EMPLEADOS.EMAIL_COORPORARIVO_EMPLEADO%TYPE,
    p_fi    IN VARCHAR2,
    p_est   IN EMPLEADOS.ESTADO_EMPLEADO%TYPE,
    p_cargo IN EMPLEADOS.ID_CARGO%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO EMPLEADOS(NUMERO_EMPLEADO, DPI_EMPLEADO, NOMBRES_EMPLEADO,
                          APELLIDOS_EMPLEADO, FECHA_NACIMIENTO_EMPLEADO, GENERO_EMPLEADO,
                          EMAIL_COORPORARIVO_EMPLEADO, FECHA_INGRESO_EMPLEADO,
                          ESTADO_EMPLEADO, ID_CARGO)
    VALUES (p_num, p_dpi, p_nom, p_ape,
            TO_DATE(p_fn, 'YYYY-MM-DD'), p_gen, p_email,
            TO_DATE(p_fi, 'YYYY-MM-DD'), NVL(p_est, 'A'), p_cargo)
    RETURNING ID_EMPLEADO INTO p_id_out;
END SP_EMPL_INS;
/

CREATE OR REPLACE PROCEDURE SP_EMPL_UPD(
    p_nom   IN EMPLEADOS.NOMBRES_EMPLEADO%TYPE,
    p_ape   IN EMPLEADOS.APELLIDOS_EMPLEADO%TYPE,
    p_est   IN EMPLEADOS.ESTADO_EMPLEADO%TYPE,
    p_cargo IN EMPLEADOS.ID_CARGO%TYPE,
    p_id    IN EMPLEADOS.ID_EMPLEADO%TYPE
) AS
BEGIN
    UPDATE EMPLEADOS
       SET NOMBRES_EMPLEADO   = NVL(p_nom,   NOMBRES_EMPLEADO),
           APELLIDOS_EMPLEADO = NVL(p_ape,   APELLIDOS_EMPLEADO),
           ESTADO_EMPLEADO    = NVL(p_est,   ESTADO_EMPLEADO),
           ID_CARGO           = NVL(p_cargo, ID_CARGO)
     WHERE ID_EMPLEADO = p_id;
END SP_EMPL_UPD;
/

CREATE OR REPLACE PROCEDURE SP_EMPL_DEL(
    p_id IN EMPLEADOS.ID_EMPLEADO%TYPE
) AS
BEGIN
    UPDATE EMPLEADOS SET ESTADO_EMPLEADO = 'I' WHERE ID_EMPLEADO = p_id;
END SP_EMPL_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- JORNADAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_JOR_INS(
    p_n   IN JORNADAS.NOMBRE_JORNADA%TYPE,
    p_c   IN JORNADAS.CODIGO_JORNADA%TYPE,
    p_hi  IN JORNADAS.HORA_IN_JORNADA%TYPE,
    p_hf  IN JORNADAS.JORA_FIN_JORNADA%TYPE,
    p_hd  IN JORNADAS.HORA_DESCANSO_JORNADA%TYPE,
    p_obs IN JORNADAS.OBSERVACIONES_JORNADA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO JORNADAS(NOMBRE_JORNADA, CODIGO_JORNADA, HORA_IN_JORNADA,
                         JORA_FIN_JORNADA, HORA_DESCANSO_JORNADA, OBSERVACIONES_JORNADA)
    VALUES (p_n, p_c, p_hi, p_hf, p_hd, p_obs)
    RETURNING ID_JORNADA INTO p_id_out;
END SP_JOR_INS;
/

CREATE OR REPLACE PROCEDURE SP_JOR_UPD(
    p_n  IN JORNADAS.NOMBRE_JORNADA%TYPE,
    p_hi IN JORNADAS.HORA_IN_JORNADA%TYPE,
    p_hf IN JORNADAS.JORA_FIN_JORNADA%TYPE,
    p_id IN JORNADAS.ID_JORNADA%TYPE
) AS
BEGIN
    UPDATE JORNADAS
       SET NOMBRE_JORNADA  = NVL(p_n,  NOMBRE_JORNADA),
           HORA_IN_JORNADA = NVL(p_hi, HORA_IN_JORNADA),
           JORA_FIN_JORNADA= NVL(p_hf, JORA_FIN_JORNADA)
     WHERE ID_JORNADA = p_id;
END SP_JOR_UPD;
/

CREATE OR REPLACE PROCEDURE SP_JOR_DEL(
    p_id IN JORNADAS.ID_JORNADA%TYPE
) AS
BEGIN
    DELETE FROM JORNADAS WHERE ID_JORNADA = p_id;
END SP_JOR_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- NÓMINA
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_NOM_INS(
    p_per    IN NOMINA.PERIODO_NOMINA%TYPE,
    p_fp     IN VARCHAR2,
    p_tb     IN NOMINA.TOTAL_BRUTO_NOMINA%TYPE,
    p_td     IN NOMINA.TOTAL_DESCUENTOS_NOMINA%TYPE,
    p_tn     IN NOMINA.TOTAL_NETO_NOMINA%TYPE,
    p_suc    IN NOMINA.ID_SUCURSAL%TYPE,
    p_ucrea  IN NOMINA.ID_USUARIO_CREA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO NOMINA(PERIODO_NOMINA, FECHA_PAGO_NOMINA, TOTAL_BRUTO_NOMINA,
                       TOTAL_DESCUENTOS_NOMINA, TOTAL_NETO_NOMINA, ESTADO_NOMINA,
                       ID_SUCURSAL, ID_USUARIO_CREA)
    VALUES (p_per, TO_DATE(p_fp, 'YYYY-MM-DD'), p_tb, p_td, p_tn, 'A', p_suc, p_ucrea)
    RETURNING ID_NOMINA INTO p_id_out;
END SP_NOM_INS;
/

CREATE OR REPLACE PROCEDURE SP_NOM_UPD(
    p_tb  IN NOMINA.TOTAL_BRUTO_NOMINA%TYPE,
    p_td  IN NOMINA.TOTAL_DESCUENTOS_NOMINA%TYPE,
    p_tn  IN NOMINA.TOTAL_NETO_NOMINA%TYPE,
    p_est IN NOMINA.ESTADO_NOMINA%TYPE,
    p_id  IN NOMINA.ID_NOMINA%TYPE
) AS
BEGIN
    UPDATE NOMINA
       SET TOTAL_BRUTO_NOMINA       = NVL(p_tb,  TOTAL_BRUTO_NOMINA),
           TOTAL_DESCUENTOS_NOMINA  = NVL(p_td,  TOTAL_DESCUENTOS_NOMINA),
           TOTAL_NETO_NOMINA        = NVL(p_tn,  TOTAL_NETO_NOMINA),
           ESTADO_NOMINA            = NVL(p_est, ESTADO_NOMINA)
     WHERE ID_NOMINA = p_id;
END SP_NOM_UPD;
/

CREATE OR REPLACE PROCEDURE SP_NOM_DEL(
    p_id IN NOMINA.ID_NOMINA%TYPE
) AS
BEGIN
    UPDATE NOMINA SET ESTADO_NOMINA = 'I' WHERE ID_NOMINA = p_id;
END SP_NOM_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- INVENTARIO - CATEGORÍAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_CATART_INS(
    p_n     IN CATEGORIAS_ARTICULO.NOMBRE_CATEGORIA_ARTICULO%TYPE,
    p_c     IN CATEGORIAS_ARTICULO.CODIGO_CATEGORIA_ARTICULO%TYPE,
    p_niv   IN CATEGORIAS_ARTICULO.NIVEL_CATEGORIA_ARTICULO%TYPE,
    p_padre IN CATEGORIAS_ARTICULO.ID_CATEGORIA_ARTICULO_PADRE%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO CATEGORIAS_ARTICULO(NOMBRE_CATEGORIA_ARTICULO, CODIGO_CATEGORIA_ARTICULO,
                                     NIVEL_CATEGORIA_ARTICULO, ID_CATEGORIA_ARTICULO_PADRE)
    VALUES (p_n, p_c, p_niv, p_padre)
    RETURNING ID_CATEGORIAS_ARTICULO INTO p_id_out;
END SP_CATART_INS;
/

CREATE OR REPLACE PROCEDURE SP_CATART_UPD(
    p_n  IN CATEGORIAS_ARTICULO.NOMBRE_CATEGORIA_ARTICULO%TYPE,
    p_id IN CATEGORIAS_ARTICULO.ID_CATEGORIAS_ARTICULO%TYPE
) AS
BEGIN
    UPDATE CATEGORIAS_ARTICULO
       SET NOMBRE_CATEGORIA_ARTICULO = NVL(p_n, NOMBRE_CATEGORIA_ARTICULO)
     WHERE ID_CATEGORIAS_ARTICULO = p_id;
END SP_CATART_UPD;
/

CREATE OR REPLACE PROCEDURE SP_CATART_DEL(
    p_id IN CATEGORIAS_ARTICULO.ID_CATEGORIAS_ARTICULO%TYPE
) AS
BEGIN
    DELETE FROM CATEGORIAS_ARTICULO WHERE ID_CATEGORIAS_ARTICULO = p_id;
END SP_CATART_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- INVENTARIO - BODEGAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_BOD_INS(
    p_c   IN BODEGAS.CODIGO_BODEGA%TYPE,
    p_n   IN BODEGAS.NOMBRE_BODEGA%TYPE,
    p_t   IN BODEGAS.TIPO_BODEGA%TYPE,
    p_d   IN BODEGAS.DIRECCION_BODEGA%TYPE,
    p_est IN BODEGAS.ESTADO_BODEGA%TYPE,
    p_suc IN BODEGAS.ID_SUCURSAL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO BODEGAS(CODIGO_BODEGA, NOMBRE_BODEGA, TIPO_BODEGA,
                        DIRECCION_BODEGA, ESTADO_BODEGA, ID_SUCURSAL)
    VALUES (p_c, p_n, p_t, p_d, NVL(p_est, 'A'), p_suc)
    RETURNING ID_BODEGA INTO p_id_out;
END SP_BOD_INS;
/

CREATE OR REPLACE PROCEDURE SP_BOD_UPD(
    p_n   IN BODEGAS.NOMBRE_BODEGA%TYPE,
    p_est IN BODEGAS.ESTADO_BODEGA%TYPE,
    p_id  IN BODEGAS.ID_BODEGA%TYPE
) AS
BEGIN
    UPDATE BODEGAS
       SET NOMBRE_BODEGA  = NVL(p_n,   NOMBRE_BODEGA),
           ESTADO_BODEGA  = NVL(p_est, ESTADO_BODEGA)
     WHERE ID_BODEGA = p_id;
END SP_BOD_UPD;
/

CREATE OR REPLACE PROCEDURE SP_BOD_DEL(
    p_id IN BODEGAS.ID_BODEGA%TYPE
) AS
BEGIN
    UPDATE BODEGAS SET ESTADO_BODEGA = 'I' WHERE ID_BODEGA = p_id;
END SP_BOD_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- INVENTARIO - STOCK
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_STOCK_INS(
    p_cd   IN NUMBER,
    p_cr   IN NUMBER,
    p_ct   IN NUMBER,
    p_cp   IN NUMBER,
    p_art  IN STOCK_ARTICULO.ID_ARTICULO%TYPE,
    p_ubod IN STOCK_ARTICULO.ID_UBICACION_BODEGA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO STOCK_ARTICULO(CANTIDAD_DISPONIBLE_STOCK_ARTICULO,
                                CANTIDAD_RESERVADA_STOCK_ARTICULO,
                                CANTIDAD_TRNASITO_STOCK_ARTICULO,
                                COSTO_PROMEDIO_STOCK_ARTICULO,
                                ID_ARTICULO, ID_UBICACION_BODEGA)
    VALUES (p_cd, NVL(p_cr, 0), NVL(p_ct, 0), NVL(p_cp, 0), p_art, p_ubod)
    RETURNING ID_STOCK_ARTICULO INTO p_id_out;
END SP_STOCK_INS;
/

CREATE OR REPLACE PROCEDURE SP_STOCK_UPD(
    p_cd IN NUMBER,
    p_cp IN NUMBER,
    p_id IN STOCK_ARTICULO.ID_STOCK_ARTICULO%TYPE
) AS
BEGIN
    UPDATE STOCK_ARTICULO
       SET CANTIDAD_DISPONIBLE_STOCK_ARTICULO = NVL(p_cd, CANTIDAD_DISPONIBLE_STOCK_ARTICULO),
           COSTO_PROMEDIO_STOCK_ARTICULO      = NVL(p_cp, COSTO_PROMEDIO_STOCK_ARTICULO)
     WHERE ID_STOCK_ARTICULO = p_id;
END SP_STOCK_UPD;
/

-- UPSERT de stock por ID_ARTICULO (usado en edición de artículo)
CREATE OR REPLACE PROCEDURE SP_STOCK_UPSERT(
    p_id_articulo IN NUMBER,
    p_stock       IN NUMBER
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM STOCK_ARTICULO WHERE ID_ARTICULO = p_id_articulo;
    IF v_count > 0 THEN
        UPDATE STOCK_ARTICULO
           SET CANTIDAD_DISPONIBLE_STOCK_ARTICULO = p_stock
         WHERE ID_ARTICULO = p_id_articulo;
    ELSE
        INSERT INTO STOCK_ARTICULO(ID_ARTICULO, CANTIDAD_DISPONIBLE_STOCK_ARTICULO,
                                    COSTO_PROMEDIO_STOCK_ARTICULO)
        VALUES (p_id_articulo, p_stock, 0);
    END IF;
END SP_STOCK_UPSERT;
/

-- Descuenta stock al crear una orden de venta
CREATE OR REPLACE PROCEDURE SP_STOCK_DESCONTAR(
    p_cant IN NUMBER,
    p_art  IN NUMBER
) AS
BEGIN
    UPDATE STOCK_ARTICULO
       SET CANTIDAD_DISPONIBLE_STOCK_ARTICULO =
           CANTIDAD_DISPONIBLE_STOCK_ARTICULO - p_cant
     WHERE ID_ARTICULO = p_art;
END SP_STOCK_DESCONTAR;
/

-- ─────────────────────────────────────────────────────────────
-- INVENTARIO - ARTÍCULOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_ART_INS(
    p_cod   IN ARTICULO.CODIGO_ARTICULO%TYPE,
    p_barra IN ARTICULO.CODIGO_BARRA_ARTICULO%TYPE,
    p_nom   IN ARTICULO.NOMBRE_ARTICULO%TYPE,
    p_desc  IN ARTICULO.DESCRIPCION_ARTICULO%TYPE,
    p_tipo  IN ARTICULO.TIPO_ARTICULO%TYPE,
    p_peso  IN ARTICULO.PESO_ARTICULO%TYPE,
    p_smin  IN ARTICULO.STOCK_MINIMO%TYPE,
    p_smax  IN ARTICULO.STOCK_MAXIMO%TYPE,
    p_est   IN ARTICULO.ESTADO_ARTICULO%TYPE,
    p_lote  IN ARTICULO.MANEJA_LOTE_ARTICULO%TYPE,
    p_serie IN ARTICULO.MANEJA_SERIE_ARTICULO%TYPE,
    p_cat   IN ARTICULO.ID_CATEGORIA_ARTICULO%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO ARTICULO(CODIGO_ARTICULO, CODIGO_BARRA_ARTICULO, NOMBRE_ARTICULO,
                          DESCRIPCION_ARTICULO, TIPO_ARTICULO, PESO_ARTICULO,
                          STOCK_MINIMO, STOCK_MAXIMO, ESTADO_ARTICULO,
                          MANEJA_LOTE_ARTICULO, MANEJA_SERIE_ARTICULO, ID_CATEGORIA_ARTICULO)
    VALUES (p_cod, p_barra, p_nom, p_desc, p_tipo, p_peso, p_smin, p_smax,
            NVL(p_est, 'A'), NVL(p_lote, 'N'), NVL(p_serie, 'N'), p_cat)
    RETURNING ID_ARTICULO INTO p_id_out;
END SP_ART_INS;
/

CREATE OR REPLACE PROCEDURE SP_ART_UPD(
    p_cod  IN ARTICULO.CODIGO_ARTICULO%TYPE,
    p_nom  IN ARTICULO.NOMBRE_ARTICULO%TYPE,
    p_desc IN ARTICULO.DESCRIPCION_ARTICULO%TYPE,
    p_tipo IN ARTICULO.TIPO_ARTICULO%TYPE,
    p_peso IN ARTICULO.PESO_ARTICULO%TYPE,
    p_smin IN ARTICULO.STOCK_MINIMO%TYPE,
    p_smax IN ARTICULO.STOCK_MAXIMO%TYPE,
    p_est  IN ARTICULO.ESTADO_ARTICULO%TYPE,
    p_cat  IN ARTICULO.ID_CATEGORIA_ARTICULO%TYPE,
    p_id   IN ARTICULO.ID_ARTICULO%TYPE
) AS
BEGIN
    UPDATE ARTICULO
       SET CODIGO_ARTICULO       = NVL(p_cod,  CODIGO_ARTICULO),
           NOMBRE_ARTICULO       = NVL(p_nom,  NOMBRE_ARTICULO),
           DESCRIPCION_ARTICULO  = NVL(p_desc, DESCRIPCION_ARTICULO),
           TIPO_ARTICULO         = NVL(p_tipo, TIPO_ARTICULO),
           PESO_ARTICULO         = NVL(p_peso, PESO_ARTICULO),
           STOCK_MINIMO          = NVL(p_smin, STOCK_MINIMO),
           STOCK_MAXIMO          = NVL(p_smax, STOCK_MAXIMO),
           ESTADO_ARTICULO       = NVL(p_est,  ESTADO_ARTICULO),
           ID_CATEGORIA_ARTICULO = NVL(p_cat,  ID_CATEGORIA_ARTICULO)
     WHERE ID_ARTICULO = p_id;
END SP_ART_UPD;
/

CREATE OR REPLACE PROCEDURE SP_ART_DEL(
    p_id IN ARTICULO.ID_ARTICULO%TYPE
) AS
BEGIN
    UPDATE ARTICULO SET ESTADO_ARTICULO = 'I' WHERE ID_ARTICULO = p_id;
END SP_ART_DEL;
/

-- UPSERT de precio en lista de precios activa (usado en edición de artículo)
CREATE OR REPLACE PROCEDURE SP_PRECIO_UPSERT(
    p_id_articulo IN NUMBER,
    p_precio      IN NUMBER
) AS
    v_id_lista NUMBER;
    v_count    NUMBER;
BEGIN
    -- 1. Buscar lista activa por fecha
    BEGIN
        SELECT ID_LISTA_PRECIOS INTO v_id_lista
          FROM LISTA_PRECIOS
         WHERE FECHA_DESDE_LISTA_PRECIOS <= SYSDATE
           AND (FECHA_HASTA_LISTA_PRECIOS IS NULL OR FECHA_HASTA_LISTA_PRECIOS >= SYSDATE)
         ORDER BY FECHA_DESDE_LISTA_PRECIOS DESC, ID_LISTA_PRECIOS ASC
         FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- 2. Si no hay activa, buscar la lista más reciente que ya contiene el artículo
            BEGIN
                SELECT ID_LISTA_PRECIOS INTO v_id_lista
                  FROM LISTA_PRECIOS LPH
                 WHERE EXISTS (SELECT 1 FROM LISTA_PRECIOS_DET LPD
                                WHERE LPD.ID_LISTA_PRECIOS = LPH.ID_LISTA_PRECIOS
                                  AND LPD.ID_ARTICULO = p_id_articulo)
                 ORDER BY LPH.FECHA_DESDE_LISTA_PRECIOS DESC, LPH.ID_LISTA_PRECIOS DESC
                 FETCH FIRST 1 ROW ONLY;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    -- 3. Cualquier lista disponible
                    BEGIN
                        SELECT ID_LISTA_PRECIOS INTO v_id_lista
                          FROM LISTA_PRECIOS
                         ORDER BY FECHA_DESDE_LISTA_PRECIOS DESC, ID_LISTA_PRECIOS DESC
                         FETCH FIRST 1 ROW ONLY;
                    EXCEPTION
                        WHEN NO_DATA_FOUND THEN
                            RETURN; -- Sin lista de precios, no hacer nada
                    END;
            END;
    END;

    SELECT COUNT(*) INTO v_count
      FROM LISTA_PRECIOS_DET
     WHERE ID_ARTICULO = p_id_articulo AND ID_LISTA_PRECIOS = v_id_lista;

    IF v_count > 0 THEN
        UPDATE LISTA_PRECIOS_DET
           SET PRECIO_LISTA_PRECIOS_DET = p_precio
         WHERE ID_ARTICULO = p_id_articulo AND ID_LISTA_PRECIOS = v_id_lista;
    ELSE
        INSERT INTO LISTA_PRECIOS_DET(ID_LISTA_PRECIOS, ID_ARTICULO,
                                       PRECIO_LISTA_PRECIOS_DET, DESCUENTO_MAX_LISTA_PRECIOS_DET)
        VALUES (v_id_lista, p_id_articulo, p_precio, 0);
    END IF;
END SP_PRECIO_UPSERT;
/

-- ─────────────────────────────────────────────────────────────
-- COMPRAS - PROVEEDORES
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_PROV_INS(
    p_c    IN PROVEEDORES.CODIGO_PROVEEDOR%TYPE,
    p_rs   IN PROVEEDORES.RAZON_SOCIAL_PROVEEDOR%TYPE,
    p_nit  IN PROVEEDORES.NIT_PROVEEDOR%TYPE,
    p_dir  IN PROVEEDORES.DIRECCION_PROVEEDOR%TYPE,
    p_tel  IN PROVEEDORES.TELEFON_PROVEEDOR%TYPE,
    p_email IN PROVEEDORES.EMAIL_PROVEEDOR%TYPE,
    p_pp   IN PROVEEDORES.PLAZO_PAGO_PROVEEDOR%TYPE,
    p_clas IN PROVEEDORES.CLASIFICACION_PROVEEDOR%TYPE,
    p_est  IN PROVEEDORES.ESTADO_PROVEEDOR%TYPE,
    p_mon  IN PROVEEDORES.ID_MONEDA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO PROVEEDORES(CODIGO_PROVEEDOR, RAZON_SOCIAL_PROVEEDOR, NIT_PROVEEDOR,
                             DIRECCION_PROVEEDOR, TELEFON_PROVEEDOR, EMAIL_PROVEEDOR,
                             PLAZO_PAGO_PROVEEDOR, CLASIFICACION_PROVEEDOR,
                             ESTADO_PROVEEDOR, ID_MONEDA)
    VALUES (p_c, p_rs, p_nit, p_dir, p_tel, p_email, p_pp, p_clas, NVL(p_est, 'A'), p_mon)
    RETURNING ID_PROVEEDOR INTO p_id_out;
END SP_PROV_INS;
/

CREATE OR REPLACE PROCEDURE SP_PROV_UPD(
    p_rs  IN PROVEEDORES.RAZON_SOCIAL_PROVEEDOR%TYPE,
    p_pp  IN PROVEEDORES.PLAZO_PAGO_PROVEEDOR%TYPE,
    p_est IN PROVEEDORES.ESTADO_PROVEEDOR%TYPE,
    p_id  IN PROVEEDORES.ID_PROVEEDOR%TYPE
) AS
BEGIN
    UPDATE PROVEEDORES
       SET RAZON_SOCIAL_PROVEEDOR = NVL(p_rs,  RAZON_SOCIAL_PROVEEDOR),
           PLAZO_PAGO_PROVEEDOR   = NVL(p_pp,  PLAZO_PAGO_PROVEEDOR),
           ESTADO_PROVEEDOR       = NVL(p_est, ESTADO_PROVEEDOR)
     WHERE ID_PROVEEDOR = p_id;
END SP_PROV_UPD;
/

CREATE OR REPLACE PROCEDURE SP_PROV_DEL(
    p_id IN PROVEEDORES.ID_PROVEEDOR%TYPE
) AS
BEGIN
    UPDATE PROVEEDORES SET ESTADO_PROVEEDOR = 'I' WHERE ID_PROVEEDOR = p_id;
END SP_PROV_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- COMPRAS - ÓRDENES DE COMPRA
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_OC_INS(
    p_num   IN ORDEN_COMPRA.NUMERO_ORDEN_COMPRA%TYPE,
    p_sub   IN ORDEN_COMPRA.SUBTOTAL_ORDEN_COMPRA%TYPE,
    p_imp   IN ORDEN_COMPRA.IMPUESTO_ORDEN_COMPRA%TYPE,
    p_tot   IN ORDEN_COMPRA.TOTAL_ORDEN_COMPRA%TYPE,
    p_prov  IN ORDEN_COMPRA.ID_PROVEEDOR%TYPE,
    p_mon   IN ORDEN_COMPRA.ID_MONEDA%TYPE,
    p_sol   IN ORDEN_COMPRA.ID_SOLICITUD_COMPRA%TYPE,
    p_ucrea IN ORDEN_COMPRA.ID_USUARIO_CREA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO ORDEN_COMPRA(NUMERO_ORDEN_COMPRA, FECHA_SOLICITUD_ORDEN_COMPRA,
                              FECHA_INGRESO_ORDEN_COMPRA, SUBTOTAL_ORDEN_COMPRA,
                              IMPUESTO_ORDEN_COMPRA, TOTAL_ORDEN_COMPRA,
                              ESTADO_ORDEN_COMPRA, ID_PROVEEDOR, ID_MONEDA,
                              ID_SOLICITUD_COMPRA, ID_USUARIO_CREA)
    VALUES (p_num, SYSDATE, SYSDATE, p_sub, p_imp, p_tot,
            'P', p_prov, p_mon, p_sol, p_ucrea)
    RETURNING ID_ORDEN_COMPRA INTO p_id_out;
END SP_OC_INS;
/

CREATE OR REPLACE PROCEDURE SP_OC_UPD(
    p_sub  IN ORDEN_COMPRA.SUBTOTAL_ORDEN_COMPRA%TYPE,
    p_imp  IN ORDEN_COMPRA.IMPUESTO_ORDEN_COMPRA%TYPE,
    p_tot  IN ORDEN_COMPRA.TOTAL_ORDEN_COMPRA%TYPE,
    p_est  IN ORDEN_COMPRA.ESTADO_ORDEN_COMPRA%TYPE,
    p_umod IN ORDEN_COMPRA.ID_USUARIO_MODIFICA%TYPE,
    p_id   IN ORDEN_COMPRA.ID_ORDEN_COMPRA%TYPE
) AS
BEGIN
    UPDATE ORDEN_COMPRA
       SET SUBTOTAL_ORDEN_COMPRA   = NVL(p_sub, SUBTOTAL_ORDEN_COMPRA),
           IMPUESTO_ORDEN_COMPRA   = NVL(p_imp, IMPUESTO_ORDEN_COMPRA),
           TOTAL_ORDEN_COMPRA      = NVL(p_tot, TOTAL_ORDEN_COMPRA),
           ESTADO_ORDEN_COMPRA     = NVL(p_est, ESTADO_ORDEN_COMPRA),
           ID_USUARIO_MODIFICA     = p_umod
     WHERE ID_ORDEN_COMPRA = p_id;
END SP_OC_UPD;
/

CREATE OR REPLACE PROCEDURE SP_OC_DEL(
    p_id IN ORDEN_COMPRA.ID_ORDEN_COMPRA%TYPE
) AS
BEGIN
    UPDATE ORDEN_COMPRA SET ESTADO_ORDEN_COMPRA = 'C' WHERE ID_ORDEN_COMPRA = p_id;
END SP_OC_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- VENTAS - CLIENTES
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_CLI_INS(
    p_c    IN CLIENTE.CODIGO_CLIENTE%TYPE,
    p_rs   IN CLIENTE.RAZON_SOCIAL_CLIENTE%TYPE,
    p_nit  IN CLIENTE.NIT_CLIENTE%TYPE,
    p_lim  IN CLIENTE.LIMITE_CREDITO_CLIENTE%TYPE,
    p_tel  IN CLIENTE.TELEFON_CLIENTE%TYPE,
    p_email IN CLIENTE.EMAIL_CLIENTE%TYPE,
    p_pp   IN CLIENTE.PLAZO_PAGO_CLIENTES%TYPE,
    p_est  IN CLIENTE.ESTADO_CLIENTE%TYPE,
    p_lp   IN CLIENTE.ID_LISTA_PRECIOS%TYPE,
    p_suc  IN CLIENTE.ID_SUCURSAL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO CLIENTE(CODIGO_CLIENTE, RAZON_SOCIAL_CLIENTE, NIT_CLIENTE,
                        LIMITE_CREDITO_CLIENTE, TELEFON_CLIENTE, EMAIL_CLIENTE,
                        PLAZO_PAGO_CLIENTES, ESTADO_CLIENTE, ID_LISTA_PRECIOS, ID_SUCURSAL)
    VALUES (p_c, p_rs, p_nit, p_lim, p_tel, p_email, p_pp, NVL(p_est, 'A'), p_lp, p_suc)
    RETURNING ID_CLIENTE INTO p_id_out;
END SP_CLI_INS;
/

CREATE OR REPLACE PROCEDURE SP_CLI_UPD(
    p_rs  IN CLIENTE.RAZON_SOCIAL_CLIENTE%TYPE,
    p_lim IN CLIENTE.LIMITE_CREDITO_CLIENTE%TYPE,
    p_est IN CLIENTE.ESTADO_CLIENTE%TYPE,
    p_id  IN CLIENTE.ID_CLIENTE%TYPE
) AS
BEGIN
    UPDATE CLIENTE
       SET RAZON_SOCIAL_CLIENTE   = NVL(p_rs,  RAZON_SOCIAL_CLIENTE),
           LIMITE_CREDITO_CLIENTE = NVL(p_lim, LIMITE_CREDITO_CLIENTE),
           ESTADO_CLIENTE         = NVL(p_est, ESTADO_CLIENTE)
     WHERE ID_CLIENTE = p_id;
END SP_CLI_UPD;
/

CREATE OR REPLACE PROCEDURE SP_CLI_DEL(
    p_id IN CLIENTE.ID_CLIENTE%TYPE
) AS
BEGIN
    UPDATE CLIENTE SET ESTADO_CLIENTE = 'I' WHERE ID_CLIENTE = p_id;
END SP_CLI_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- VENTAS - LISTA DE PRECIOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_LP_INS(
    p_n   IN LISTA_PRECIOS.NOMBRE_LISTA_PRECIOS%TYPE,
    p_fd  IN VARCHAR2,
    p_fh  IN VARCHAR2,
    p_mon IN LISTA_PRECIOS.ID_MONEDA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO LISTA_PRECIOS(NOMBRE_LISTA_PRECIOS, FECHA_DESDE_LISTA_PRECIOS,
                               FECHA_HASTA_LISTA_PRECIOS, ID_MONEDA)
    VALUES (p_n, TO_DATE(p_fd, 'YYYY-MM-DD'), TO_DATE(p_fh, 'YYYY-MM-DD'), p_mon)
    RETURNING ID_LISTA_PRECIOS INTO p_id_out;
END SP_LP_INS;
/

CREATE OR REPLACE PROCEDURE SP_LP_DEL(
    p_id IN LISTA_PRECIOS.ID_LISTA_PRECIOS%TYPE
) AS
BEGIN
    DELETE FROM LISTA_PRECIOS WHERE ID_LISTA_PRECIOS = p_id;
END SP_LP_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- VENTAS - ÓRDENES DE VENTA
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_OV_INS(
    p_num   IN ORDEN_VENTA.NUMERO_ORDEN_VENTA%TYPE,
    p_sub   IN ORDEN_VENTA.SUBTOTAL_ORDEN_VENTA%TYPE,
    p_imp   IN ORDEN_VENTA.IMPUESTO_ORDEN_VENTA%TYPE,
    p_tot   IN ORDEN_VENTA.TOTAL_ORDEN_VENTA%TYPE,
    p_cli   IN ORDEN_VENTA.ID_CLIENTE%TYPE,
    p_ucrea IN ORDEN_VENTA.ID_USUARIO_CREA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO ORDEN_VENTA(NUMERO_ORDEN_VENTA, FECHA_SOLICITUD_ORDEN_VENTA,
                             FECHA_ENTREGA_ORDEN_VENTA, SUBTOTAL_ORDEN_VENTA,
                             DESCUENTO_ORDEN_VENTA, IMPUESTO_ORDEN_VENTA,
                             TOTAL_ORDEN_VENTA, ESTADO_ORDEN_VENTA, ID_CLIENTE, ID_USUARIO_CREA)
    VALUES (p_num, SYSDATE, SYSDATE + 7, p_sub, 0, p_imp, p_tot, 'P', p_cli, p_ucrea)
    RETURNING ID_ORDEN_VENTA INTO p_id_out;
END SP_OV_INS;
/

CREATE OR REPLACE PROCEDURE SP_OV_DET_INS(
    p_cant   IN NUMBER,
    p_precio IN NUMBER,
    p_sub    IN NUMBER,
    p_art    IN ORDEN_VENTA_DETALLE.ID_ARTICULO%TYPE,
    p_ov     IN ORDEN_VENTA_DETALLE.ID_ORDEN_VENTA%TYPE
) AS
BEGIN
    INSERT INTO ORDEN_VENTA_DETALLE(CANTIDAD_SOLICITUD_VENTA_COMPRA_DETALLE,
                                     CANTIDAD_ENTREGADA_VENTA_COMPRA_DETALLE,
                                     PRECIO_UNITARIO_ORDEN_VENTA_DETALLE,
                                     SUBTOTAL_ORDEN_VENTA_DETALLE,
                                     ESTADO_ORDEN_VENTA_DETALLE,
                                     ID_ARTICULO, ID_ORDEN_VENTA)
    VALUES (p_cant, 0, p_precio, p_sub, 'P', p_art, p_ov);
END SP_OV_DET_INS;
/

CREATE OR REPLACE PROCEDURE SP_OV_UPD(
    p_sub  IN ORDEN_VENTA.SUBTOTAL_ORDEN_VENTA%TYPE,
    p_imp  IN ORDEN_VENTA.IMPUESTO_ORDEN_VENTA%TYPE,
    p_tot  IN ORDEN_VENTA.TOTAL_ORDEN_VENTA%TYPE,
    p_est  IN ORDEN_VENTA.ESTADO_ORDEN_VENTA%TYPE,
    p_umod IN ORDEN_VENTA.ID_USUARIO_MODIFICA%TYPE,
    p_id   IN ORDEN_VENTA.ID_ORDEN_VENTA%TYPE
) AS
BEGIN
    UPDATE ORDEN_VENTA
       SET SUBTOTAL_ORDEN_VENTA  = NVL(p_sub, SUBTOTAL_ORDEN_VENTA),
           IMPUESTO_ORDEN_VENTA  = NVL(p_imp, IMPUESTO_ORDEN_VENTA),
           TOTAL_ORDEN_VENTA     = NVL(p_tot, TOTAL_ORDEN_VENTA),
           ESTADO_ORDEN_VENTA    = NVL(p_est, ESTADO_ORDEN_VENTA),
           ID_USUARIO_MODIFICA   = p_umod
     WHERE ID_ORDEN_VENTA = p_id;
END SP_OV_UPD;
/

-- ─────────────────────────────────────────────────────────────
-- VENTAS - FACTURAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_FV_INS(
    p_s     IN FACTURA_VENTA.SERIE_FACTURA_VENTA%TYPE,
    p_cor   IN FACTURA_VENTA.CORRELATIVO_FACTURA_VENTA%TYPE,
    p_tot   IN FACTURA_VENTA.TOTAL_FACTURA_VENTA%TYPE,
    p_sm    IN FACTURA_VENTA.ID_SALIDA_MERCADERIA%TYPE,
    p_ucrea IN FACTURA_VENTA.ID_USUARIO_CREA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO FACTURA_VENTA(SERIE_FACTURA_VENTA, CORRELATIVO_FACTURA_VENTA,
                               FECHA_SALIDA_FACTURA_VENTA, FECHA_FACTURA_VENTA,
                               ESTADO_SALIDA_MERCADERIA, TOTAL_FACTURA_VENTA,
                               ID_SALIDA_MERCADERIA, ID_USUARIO_CREA)
    VALUES (p_s, p_cor, SYSDATE, SYSDATE, 'A', p_tot, p_sm, p_ucrea)
    RETURNING ID_FACTURA_VENTA INTO p_id_out;
END SP_FV_INS;
/

CREATE OR REPLACE PROCEDURE SP_FV_UPD(
    p_est IN FACTURA_VENTA.ESTADO_SALIDA_MERCADERIA%TYPE,
    p_id  IN FACTURA_VENTA.ID_FACTURA_VENTA%TYPE
) AS
BEGIN
    UPDATE FACTURA_VENTA
       SET ESTADO_SALIDA_MERCADERIA = NVL(p_est, ESTADO_SALIDA_MERCADERIA)
     WHERE ID_FACTURA_VENTA = p_id;
END SP_FV_UPD;
/

CREATE OR REPLACE PROCEDURE SP_FV_DEL(
    p_id IN FACTURA_VENTA.ID_FACTURA_VENTA%TYPE
) AS
BEGIN
    UPDATE FACTURA_VENTA SET ESTADO_SALIDA_MERCADERIA = 'C' WHERE ID_FACTURA_VENTA = p_id;
END SP_FV_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- VENTAS - DEVOLUCIONES
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_DV_INS(
    p_num IN DEVOLUCION_VENTA.NUMERO_DEVOLUCION%TYPE,
    p_mot IN DEVOLUCION_VENTA.MOTIVO_DEVOLUCION%TYPE,
    p_tot IN DEVOLUCION_VENTA.TOTAL_DEVOLUCION_VENTA%TYPE,
    p_sm  IN DEVOLUCION_VENTA.ID_SALIDA_MERCADERIA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO DEVOLUCION_VENTA(NUMERO_DEVOLUCION, MOTIVO_DEVOLUCION,
                                  FECHA_DEVOLUCION_VENTA, TOTAL_DEVOLUCION_VENTA,
                                  ESTADO_DEVOLUCION_VENTA, ID_SALIDA_MERCADERIA)
    VALUES (p_num, p_mot, SYSDATE, p_tot, 'P', p_sm)
    RETURNING ID_DEVOLUCION_VENTA INTO p_id_out;
END SP_DV_INS;
/

CREATE OR REPLACE PROCEDURE SP_DV_UPD(
    p_est IN DEVOLUCION_VENTA.ESTADO_DEVOLUCION_VENTA%TYPE,
    p_id  IN DEVOLUCION_VENTA.ID_DEVOLUCION_VENTA%TYPE
) AS
BEGIN
    UPDATE DEVOLUCION_VENTA
       SET ESTADO_DEVOLUCION_VENTA = NVL(p_est, ESTADO_DEVOLUCION_VENTA)
     WHERE ID_DEVOLUCION_VENTA = p_id;
END SP_DV_UPD;
/

CREATE OR REPLACE PROCEDURE SP_DV_DEL(
    p_id IN DEVOLUCION_VENTA.ID_DEVOLUCION_VENTA%TYPE
) AS
BEGIN
    UPDATE DEVOLUCION_VENTA SET ESTADO_DEVOLUCION_VENTA = 'C' WHERE ID_DEVOLUCION_VENTA = p_id;
END SP_DV_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- PRODUCCIÓN - CENTROS DE TRABAJO
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_CT_INS(
    p_c   IN CENTRO_TRABAJO.CODIGO_CENTRO_TRABAJO%TYPE,
    p_n   IN CENTRO_TRABAJO.NOMBRE_CENTRO_TRABAJO%TYPE,
    p_ch  IN CENTRO_TRABAJO.CAPACIDAD_HORA%TYPE,
    p_vh  IN CENTRO_TRABAJO.VOSTO_HORA_CENTRO_TRABAJO%TYPE,
    p_est IN CENTRO_TRABAJO.ESTADO_CENTRO_TRABAJO%TYPE,
    p_suc IN CENTRO_TRABAJO.ID_SUCURSAL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO CENTRO_TRABAJO(CODIGO_CENTRO_TRABAJO, NOMBRE_CENTRO_TRABAJO,
                                CAPACIDAD_HORA, VOSTO_HORA_CENTRO_TRABAJO,
                                ESTADO_CENTRO_TRABAJO, ID_SUCURSAL)
    VALUES (p_c, p_n, p_ch, p_vh, NVL(p_est, 'A'), p_suc)
    RETURNING ID_CENTRO_TRABAJO INTO p_id_out;
END SP_CT_INS;
/

CREATE OR REPLACE PROCEDURE SP_CT_UPD(
    p_n   IN CENTRO_TRABAJO.NOMBRE_CENTRO_TRABAJO%TYPE,
    p_est IN CENTRO_TRABAJO.ESTADO_CENTRO_TRABAJO%TYPE,
    p_id  IN CENTRO_TRABAJO.ID_CENTRO_TRABAJO%TYPE
) AS
BEGIN
    UPDATE CENTRO_TRABAJO
       SET NOMBRE_CENTRO_TRABAJO  = NVL(p_n,   NOMBRE_CENTRO_TRABAJO),
           ESTADO_CENTRO_TRABAJO  = NVL(p_est, ESTADO_CENTRO_TRABAJO)
     WHERE ID_CENTRO_TRABAJO = p_id;
END SP_CT_UPD;
/

CREATE OR REPLACE PROCEDURE SP_CT_DEL(
    p_id IN CENTRO_TRABAJO.ID_CENTRO_TRABAJO%TYPE
) AS
BEGIN
    UPDATE CENTRO_TRABAJO SET ESTADO_CENTRO_TRABAJO = 'I' WHERE ID_CENTRO_TRABAJO = p_id;
END SP_CT_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- PRODUCCIÓN - ÓRDENES DE PRODUCCIÓN
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_OP_INS(
    p_cod   IN ORDEN_PRODUCCION.CODIGO_ORDEN_PRODUCCION%TYPE,
    p_fi    IN VARCHAR2,
    p_ff    IN VARCHAR2,
    p_cp    IN ORDEN_PRODUCCION.CANTIDAD_PLANIFICADA_ORDEN_PRODUCCION%TYPE,
    p_lm    IN ORDEN_PRODUCCION.ID_LISTA_MATERIALES%TYPE,
    p_ct    IN ORDEN_PRODUCCION.ID_CENTRO_TRABAJO%TYPE,
    p_suc   IN ORDEN_PRODUCCION.ID_SUCURSAL%TYPE,
    p_ucrea IN ORDEN_PRODUCCION.ID_USUARIO_CREA%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO ORDEN_PRODUCCION(CODIGO_ORDEN_PRODUCCION,
                                  FECHA_IN_ORDEN_PRODUCCION, FECHA_FIN_ORDEN_PRODUCCION,
                                  CANTIDAD_PLANIFICADA_ORDEN_PRODUCCION,
                                  CANTIDAD_PRODUCIDA_ORIDEN_PRODUCCION,
                                  CANTIDAD_MERMA_ORDEN_PRODUCCION,
                                  ESTADO_ORDEN_PRODUCCION, ID_LISTA_MATERIALES,
                                  ID_CENTRO_TRABAJO, ID_SUCURSAL, ID_USUARIO_CREA)
    VALUES (p_cod, TO_DATE(p_fi, 'YYYY-MM-DD'), TO_DATE(p_ff, 'YYYY-MM-DD'),
            p_cp, 0, 0, 'P', p_lm, p_ct, p_suc, p_ucrea)
    RETURNING ID_ORDEN_PRODUCCION INTO p_id_out;
END SP_OP_INS;
/

CREATE OR REPLACE PROCEDURE SP_OP_UPD(
    p_cplan IN ORDEN_PRODUCCION.CANTIDAD_PLANIFICADA_ORDEN_PRODUCCION%TYPE,
    p_cprod IN NUMBER,
    p_est   IN ORDEN_PRODUCCION.ESTADO_ORDEN_PRODUCCION%TYPE,
    p_umod  IN ORDEN_PRODUCCION.ID_USUARIO_MODIFICA%TYPE,
    p_id    IN ORDEN_PRODUCCION.ID_ORDEN_PRODUCCION%TYPE
) AS
BEGIN
    UPDATE ORDEN_PRODUCCION
       SET CANTIDAD_PLANIFICADA_ORDEN_PRODUCCION = NVL(p_cplan, CANTIDAD_PLANIFICADA_ORDEN_PRODUCCION),
           CANTIDAD_PRODUCIDA_ORIDEN_PRODUCCION  = NVL(p_cprod, CANTIDAD_PRODUCIDA_ORIDEN_PRODUCCION),
           ESTADO_ORDEN_PRODUCCION               = NVL(p_est,   ESTADO_ORDEN_PRODUCCION),
           ID_USUARIO_MODIFICA                   = p_umod
     WHERE ID_ORDEN_PRODUCCION = p_id;
END SP_OP_UPD;
/

CREATE OR REPLACE PROCEDURE SP_OP_DEL(
    p_id IN ORDEN_PRODUCCION.ID_ORDEN_PRODUCCION%TYPE
) AS
BEGIN
    UPDATE ORDEN_PRODUCCION SET ESTADO_ORDEN_PRODUCCION = 'R' WHERE ID_ORDEN_PRODUCCION = p_id;
END SP_OP_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- LOGÍSTICA - VEHÍCULOS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_VEH_INS(
    p_p    IN VEHICULO.PLACA_VEHICULO%TYPE,
    p_m    IN VEHICULO.MARCA_VEHICULO%TYPE,
    p_mod  IN VEHICULO.MODELO_VEHICULO%TYPE,
    p_t    IN VEHICULO.TIPO_VEHICULO%TYPE,
    p_cap  IN VEHICULO.CAPACIDAD_KG_VEHICULO%TYPE,
    p_kult IN VEHICULO.KM_ULT_SERV_VEHICULO%TYPE,
    p_ksig IN VEHICULO.KM_SIG_SERV_VEHICULO%TYPE,
    p_est  IN VEHICULO.ESTADO_VEHICULO%TYPE,
    p_suc  IN VEHICULO.ID_SUCURSAL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO VEHICULO(PLACA_VEHICULO, MARCA_VEHICULO, MODELO_VEHICULO,
                          TIPO_VEHICULO, CAPACIDAD_KG_VEHICULO,
                          KM_ULT_SERV_VEHICULO, KM_SIG_SERV_VEHICULO,
                          ESTADO_VEHICULO, ID_SUCURSAL)
    VALUES (p_p, p_m, p_mod, p_t, p_cap, p_kult, p_ksig, NVL(p_est, 'A'), p_suc)
    RETURNING ID_VEHICULO INTO p_id_out;
END SP_VEH_INS;
/

CREATE OR REPLACE PROCEDURE SP_VEH_UPD(
    p_est  IN VEHICULO.ESTADO_VEHICULO%TYPE,
    p_ksig IN VEHICULO.KM_SIG_SERV_VEHICULO%TYPE,
    p_id   IN VEHICULO.ID_VEHICULO%TYPE
) AS
BEGIN
    UPDATE VEHICULO
       SET ESTADO_VEHICULO      = NVL(p_est,  ESTADO_VEHICULO),
           KM_SIG_SERV_VEHICULO = NVL(p_ksig, KM_SIG_SERV_VEHICULO)
     WHERE ID_VEHICULO = p_id;
END SP_VEH_UPD;
/

CREATE OR REPLACE PROCEDURE SP_VEH_DEL(
    p_id IN VEHICULO.ID_VEHICULO%TYPE
) AS
BEGIN
    UPDATE VEHICULO SET ESTADO_VEHICULO = 'I' WHERE ID_VEHICULO = p_id;
END SP_VEH_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- LOGÍSTICA - TRANSPORTISTAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_TRANS_INS(
    p_n    IN TRANSPORTISTA.NOMBRE_TRANSPORTISTA%TYPE,
    p_a    IN TRANSPORTISTA.APELLIDOS_TRANSPORTISTA%TYPE,
    p_lic  IN TRANSPORTISTA.LICENCIA_TRANSPORTISTA%TYPE,
    p_dpi  IN TRANSPORTISTA.DPI_TRANPORTISTA%TYPE,
    p_tlic IN TRANSPORTISTA.TIPO_LIC_TRANSPORTISTA%TYPE,
    p_est  IN TRANSPORTISTA.ESTADO_TRANSPORTISTA%TYPE,
    p_emp  IN TRANSPORTISTA.ID_EMPLEADO%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO TRANSPORTISTA(NOMBRE_TRANSPORTISTA, APELLIDOS_TRANSPORTISTA,
                               LICENCIA_TRANSPORTISTA, DPI_TRANPORTISTA,
                               TIPO_LIC_TRANSPORTISTA, ESTADO_TRANSPORTISTA, ID_EMPLEADO)
    VALUES (p_n, p_a, p_lic, p_dpi, p_tlic, NVL(p_est, 'A'), p_emp)
    RETURNING ID_TRANSPORTISTA INTO p_id_out;
END SP_TRANS_INS;
/

CREATE OR REPLACE PROCEDURE SP_TRANS_UPD(
    p_est IN TRANSPORTISTA.ESTADO_TRANSPORTISTA%TYPE,
    p_id  IN TRANSPORTISTA.ID_TRANSPORTISTA%TYPE
) AS
BEGIN
    UPDATE TRANSPORTISTA
       SET ESTADO_TRANSPORTISTA = NVL(p_est, ESTADO_TRANSPORTISTA)
     WHERE ID_TRANSPORTISTA = p_id;
END SP_TRANS_UPD;
/

CREATE OR REPLACE PROCEDURE SP_TRANS_DEL(
    p_id IN TRANSPORTISTA.ID_TRANSPORTISTA%TYPE
) AS
BEGIN
    UPDATE TRANSPORTISTA SET ESTADO_TRANSPORTISTA = 'I' WHERE ID_TRANSPORTISTA = p_id;
END SP_TRANS_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- LOGÍSTICA - ÓRDENES DE DESPACHO
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_OD_INS(
    p_nom  IN ORDEN_DESPACHADO.NOMBRE_ORDEN_DESPACHO%TYPE,
    p_fent IN VARCHAR2,
    p_peso IN ORDEN_DESPACHADO.PESO_KG_TOTAL_ORDEN_DESPACHO%TYPE,
    p_veh  IN ORDEN_DESPACHADO.ID_VEHICULO%TYPE,
    p_trans IN ORDEN_DESPACHADO.ID_TRANSPORTISTA%TYPE,
    p_suc  IN ORDEN_DESPACHADO.ID_SUCURSAL%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO ORDEN_DESPACHADO(NOMBRE_ORDEN_DESPACHO, FECHA_CREA_ORDEN_DESPACHO,
                                  FECHA_ENTREGA_ORDEN_DESPACHO,
                                  PESO_KG_TOTAL_ORDEN_DESPACHO, ESTADO_ORDEN_DESPACHADO,
                                  ID_VEHICULO, ID_TRANSPORTISTA, ID_SUCURSAL)
    VALUES (p_nom, SYSDATE, TO_DATE(p_fent, 'YYYY-MM-DD'),
            p_peso, 'P', p_veh, p_trans, p_suc)
    RETURNING ID_ORDEN_DESPACHO INTO p_id_out;
END SP_OD_INS;
/

CREATE OR REPLACE PROCEDURE SP_OD_UPD(
    p_est IN ORDEN_DESPACHADO.ESTADO_ORDEN_DESPACHADO%TYPE,
    p_id  IN ORDEN_DESPACHADO.ID_ORDEN_DESPACHO%TYPE
) AS
BEGIN
    UPDATE ORDEN_DESPACHADO
       SET ESTADO_ORDEN_DESPACHADO = NVL(p_est, ESTADO_ORDEN_DESPACHADO)
     WHERE ID_ORDEN_DESPACHO = p_id;
END SP_OD_UPD;
/

CREATE OR REPLACE PROCEDURE SP_OD_DEL(
    p_id IN ORDEN_DESPACHADO.ID_ORDEN_DESPACHO%TYPE
) AS
BEGIN
    UPDATE ORDEN_DESPACHADO SET ESTADO_ORDEN_DESPACHADO = 'C' WHERE ID_ORDEN_DESPACHO = p_id;
END SP_OD_DEL;
/

-- ─────────────────────────────────────────────────────────────
-- LOGÍSTICA - ENTREGAS
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE SP_ENT_INS(
    p_obs IN ENTREGA."OBSERVACIÓN_ENTREGA"%TYPE,
    p_desp IN ENTREGA.ID_DESPACHO_DETALLE%TYPE,
    p_id_out OUT NUMBER
) AS
BEGIN
    INSERT INTO ENTREGA(FECHA_ENTREGA, "OBSERVACIÓN_ENTREGA", ID_DESPACHO_DETALLE)
    VALUES (SYSDATE, p_obs, p_desp)
    RETURNING ID_ENTREGA INTO p_id_out;
END SP_ENT_INS;
/

CREATE OR REPLACE PROCEDURE SP_ENT_UPD(
    p_obs IN ENTREGA."OBSERVACIÓN_ENTREGA"%TYPE,
    p_id  IN ENTREGA.ID_ENTREGA%TYPE
) AS
BEGIN
    UPDATE ENTREGA
       SET "OBSERVACIÓN_ENTREGA" = NVL(p_obs, "OBSERVACIÓN_ENTREGA")
     WHERE ID_ENTREGA = p_id;
END SP_ENT_UPD;
/

CREATE OR REPLACE PROCEDURE SP_ENT_DEL(
    p_id IN ENTREGA.ID_ENTREGA%TYPE
) AS
BEGIN
    DELETE FROM ENTREGA WHERE ID_ENTREGA = p_id;
END SP_ENT_DEL;
/
